namespace ProjetoJeffersonADM
{
    partial class EditarClientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditarClientes));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.idCliente_label = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.label = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bairroCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cidadeCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nomeCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ruaCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.telCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.estadoCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cpfCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rgcli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.idCliente_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.emailCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // idCliente_label
            // 
            this.idCliente_label.AllowParentOverrides = false;
            this.idCliente_label.AutoEllipsis = false;
            this.idCliente_label.Cursor = System.Windows.Forms.Cursors.Default;
            this.idCliente_label.CursorType = System.Windows.Forms.Cursors.Default;
            this.idCliente_label.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idCliente_label.ForeColor = System.Drawing.Color.Navy;
            this.idCliente_label.Location = new System.Drawing.Point(13, 15);
            this.idCliente_label.Name = "idCliente_label";
            this.idCliente_label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.idCliente_label.Size = new System.Drawing.Size(104, 22);
            this.idCliente_label.TabIndex = 17;
            this.idCliente_label.Text = "ID do Cliente:";
            this.idCliente_label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.idCliente_label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.idCliente_label.Click += new System.EventHandler(this.idCliente_label_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 156);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(111, 22);
            this.bunifuLabel2.TabIndex = 19;
            this.bunifuLabel2.Text = "RG do Cliente:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel3.Location = new System.Drawing.Point(12, 234);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(118, 22);
            this.bunifuLabel3.TabIndex = 21;
            this.bunifuLabel3.Text = "CPF do Cliente:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.Click += new System.EventHandler(this.bunifuLabel3_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel4.Location = new System.Drawing.Point(412, 233);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(57, 22);
            this.bunifuLabel4.TabIndex = 23;
            this.bunifuLabel4.Text = "Estado:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // label
            // 
            this.label.AllowParentOverrides = false;
            this.label.AutoEllipsis = false;
            this.label.CursorType = null;
            this.label.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label.ForeColor = System.Drawing.Color.Navy;
            this.label.Location = new System.Drawing.Point(13, 311);
            this.label.Name = "label";
            this.label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.label.Size = new System.Drawing.Size(159, 22);
            this.label.TabIndex = 25;
            this.label.Text = "Telefone do Cliente:";
            this.label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel6.Location = new System.Drawing.Point(412, 15);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(34, 22);
            this.bunifuLabel6.TabIndex = 27;
            this.bunifuLabel6.Text = "Rua:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel5.Location = new System.Drawing.Point(12, 90);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(135, 22);
            this.bunifuLabel5.TabIndex = 29;
            this.bunifuLabel5.Text = "Nome do Cliente:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel7.Location = new System.Drawing.Point(412, 156);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(58, 22);
            this.bunifuLabel7.TabIndex = 31;
            this.bunifuLabel7.Text = "Cidade:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.Click += new System.EventHandler(this.bunifuLabel7_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel1.Location = new System.Drawing.Point(412, 90);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(50, 22);
            this.bunifuLabel1.TabIndex = 33;
            this.bunifuLabel1.Text = "Bairro:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bairroCli_txt
            // 
            this.bairroCli_txt.AcceptsReturn = false;
            this.bairroCli_txt.AcceptsTab = false;
            this.bairroCli_txt.AnimationSpeed = 200;
            this.bairroCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bairroCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bairroCli_txt.AutoSizeHeight = false;
            this.bairroCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.bairroCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bairroCli_txt.BackgroundImage")));
            this.bairroCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bairroCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bairroCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bairroCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.bairroCli_txt.BorderRadius = 1;
            this.bairroCli_txt.BorderThickness = 0;
            this.bairroCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bairroCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bairroCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bairroCli_txt.DefaultText = "";
            this.bairroCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bairroCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.bairroCli_txt.HideSelection = true;
            this.bairroCli_txt.IconLeft = null;
            this.bairroCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroCli_txt.IconPadding = 10;
            this.bairroCli_txt.IconRight = null;
            this.bairroCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroCli_txt.Lines = new string[0];
            this.bairroCli_txt.Location = new System.Drawing.Point(412, 118);
            this.bairroCli_txt.MaxLength = 32767;
            this.bairroCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.bairroCli_txt.Modified = false;
            this.bairroCli_txt.Multiline = true;
            this.bairroCli_txt.Name = "bairroCli_txt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroCli_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bairroCli_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroCli_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties4.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties4.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroCli_txt.OnIdleState = stateProperties4;
            this.bairroCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.bairroCli_txt.PasswordChar = '\0';
            this.bairroCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bairroCli_txt.PlaceholderText = "Serraria";
            this.bairroCli_txt.ReadOnly = false;
            this.bairroCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bairroCli_txt.SelectedText = "";
            this.bairroCli_txt.SelectionLength = 0;
            this.bairroCli_txt.SelectionStart = 0;
            this.bairroCli_txt.ShortcutsEnabled = true;
            this.bairroCli_txt.Size = new System.Drawing.Size(349, 29);
            this.bairroCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bairroCli_txt.TabIndex = 32;
            this.bairroCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bairroCli_txt.TextMarginBottom = 0;
            this.bairroCli_txt.TextMarginLeft = 3;
            this.bairroCli_txt.TextMarginTop = 0;
            this.bairroCli_txt.TextPlaceholder = "Serraria";
            this.bairroCli_txt.UseSystemPasswordChar = false;
            this.bairroCli_txt.WordWrap = true;
            // 
            // cidadeCli_txt
            // 
            this.cidadeCli_txt.AcceptsReturn = false;
            this.cidadeCli_txt.AcceptsTab = false;
            this.cidadeCli_txt.AnimationSpeed = 200;
            this.cidadeCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cidadeCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cidadeCli_txt.AutoSizeHeight = false;
            this.cidadeCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.cidadeCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cidadeCli_txt.BackgroundImage")));
            this.cidadeCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cidadeCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cidadeCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cidadeCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.cidadeCli_txt.BorderRadius = 1;
            this.cidadeCli_txt.BorderThickness = 0;
            this.cidadeCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cidadeCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cidadeCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cidadeCli_txt.DefaultText = "";
            this.cidadeCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.cidadeCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.cidadeCli_txt.HideSelection = true;
            this.cidadeCli_txt.IconLeft = null;
            this.cidadeCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeCli_txt.IconPadding = 10;
            this.cidadeCli_txt.IconRight = null;
            this.cidadeCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeCli_txt.Lines = new string[0];
            this.cidadeCli_txt.Location = new System.Drawing.Point(412, 184);
            this.cidadeCli_txt.MaxLength = 32767;
            this.cidadeCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cidadeCli_txt.Modified = false;
            this.cidadeCli_txt.Multiline = true;
            this.cidadeCli_txt.Name = "cidadeCli_txt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeCli_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cidadeCli_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeCli_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties8.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties8.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeCli_txt.OnIdleState = stateProperties8;
            this.cidadeCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.cidadeCli_txt.PasswordChar = '\0';
            this.cidadeCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cidadeCli_txt.PlaceholderText = "Diadema";
            this.cidadeCli_txt.ReadOnly = false;
            this.cidadeCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cidadeCli_txt.SelectedText = "";
            this.cidadeCli_txt.SelectionLength = 0;
            this.cidadeCli_txt.SelectionStart = 0;
            this.cidadeCli_txt.ShortcutsEnabled = true;
            this.cidadeCli_txt.Size = new System.Drawing.Size(349, 29);
            this.cidadeCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cidadeCli_txt.TabIndex = 30;
            this.cidadeCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.cidadeCli_txt.TextMarginBottom = 0;
            this.cidadeCli_txt.TextMarginLeft = 3;
            this.cidadeCli_txt.TextMarginTop = 0;
            this.cidadeCli_txt.TextPlaceholder = "Diadema";
            this.cidadeCli_txt.UseSystemPasswordChar = false;
            this.cidadeCli_txt.WordWrap = true;
            this.cidadeCli_txt.TextChanged += new System.EventHandler(this.corProd_txt_TextChanged);
            // 
            // nomeCli_txt
            // 
            this.nomeCli_txt.AcceptsReturn = false;
            this.nomeCli_txt.AcceptsTab = false;
            this.nomeCli_txt.AnimationSpeed = 200;
            this.nomeCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomeCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomeCli_txt.AutoSizeHeight = false;
            this.nomeCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.nomeCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomeCli_txt.BackgroundImage")));
            this.nomeCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nomeCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomeCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nomeCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.nomeCli_txt.BorderRadius = 1;
            this.nomeCli_txt.BorderThickness = 0;
            this.nomeCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomeCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomeCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomeCli_txt.DefaultText = "";
            this.nomeCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.nomeCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.nomeCli_txt.HideSelection = true;
            this.nomeCli_txt.IconLeft = null;
            this.nomeCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeCli_txt.IconPadding = 10;
            this.nomeCli_txt.IconRight = null;
            this.nomeCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeCli_txt.Lines = new string[0];
            this.nomeCli_txt.Location = new System.Drawing.Point(12, 118);
            this.nomeCli_txt.MaxLength = 32767;
            this.nomeCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomeCli_txt.Modified = false;
            this.nomeCli_txt.Multiline = true;
            this.nomeCli_txt.Name = "nomeCli_txt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeCli_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomeCli_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeCli_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeCli_txt.OnIdleState = stateProperties12;
            this.nomeCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.nomeCli_txt.PasswordChar = '\0';
            this.nomeCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nomeCli_txt.PlaceholderText = "Ronaldo Baiano";
            this.nomeCli_txt.ReadOnly = false;
            this.nomeCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomeCli_txt.SelectedText = "";
            this.nomeCli_txt.SelectionLength = 0;
            this.nomeCli_txt.SelectionStart = 0;
            this.nomeCli_txt.ShortcutsEnabled = true;
            this.nomeCli_txt.Size = new System.Drawing.Size(349, 29);
            this.nomeCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomeCli_txt.TabIndex = 28;
            this.nomeCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.nomeCli_txt.TextMarginBottom = 0;
            this.nomeCli_txt.TextMarginLeft = 3;
            this.nomeCli_txt.TextMarginTop = 0;
            this.nomeCli_txt.TextPlaceholder = "Ronaldo Baiano";
            this.nomeCli_txt.UseSystemPasswordChar = false;
            this.nomeCli_txt.WordWrap = true;
            // 
            // ruaCli_txt
            // 
            this.ruaCli_txt.AcceptsReturn = false;
            this.ruaCli_txt.AcceptsTab = false;
            this.ruaCli_txt.AnimationSpeed = 200;
            this.ruaCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ruaCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ruaCli_txt.AutoSizeHeight = false;
            this.ruaCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ruaCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ruaCli_txt.BackgroundImage")));
            this.ruaCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ruaCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ruaCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ruaCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.ruaCli_txt.BorderRadius = 1;
            this.ruaCli_txt.BorderThickness = 0;
            this.ruaCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.ruaCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ruaCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ruaCli_txt.DefaultText = "";
            this.ruaCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.ruaCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.ruaCli_txt.HideSelection = true;
            this.ruaCli_txt.IconLeft = null;
            this.ruaCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaCli_txt.IconPadding = 10;
            this.ruaCli_txt.IconRight = null;
            this.ruaCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaCli_txt.Lines = new string[0];
            this.ruaCli_txt.Location = new System.Drawing.Point(412, 43);
            this.ruaCli_txt.MaxLength = 32767;
            this.ruaCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ruaCli_txt.Modified = false;
            this.ruaCli_txt.Multiline = true;
            this.ruaCli_txt.Name = "ruaCli_txt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaCli_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ruaCli_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaCli_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaCli_txt.OnIdleState = stateProperties16;
            this.ruaCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.ruaCli_txt.PasswordChar = '\0';
            this.ruaCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ruaCli_txt.PlaceholderText = "Guarani 114";
            this.ruaCli_txt.ReadOnly = false;
            this.ruaCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ruaCli_txt.SelectedText = "";
            this.ruaCli_txt.SelectionLength = 0;
            this.ruaCli_txt.SelectionStart = 0;
            this.ruaCli_txt.ShortcutsEnabled = true;
            this.ruaCli_txt.Size = new System.Drawing.Size(349, 29);
            this.ruaCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ruaCli_txt.TabIndex = 26;
            this.ruaCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.ruaCli_txt.TextMarginBottom = 0;
            this.ruaCli_txt.TextMarginLeft = 3;
            this.ruaCli_txt.TextMarginTop = 0;
            this.ruaCli_txt.TextPlaceholder = "Guarani 114";
            this.ruaCli_txt.UseSystemPasswordChar = false;
            this.ruaCli_txt.WordWrap = true;
            this.ruaCli_txt.TextChanged += new System.EventHandler(this.tamanhoProd_txt_TextChanged);
            // 
            // telCli_txt
            // 
            this.telCli_txt.AcceptsReturn = false;
            this.telCli_txt.AcceptsTab = false;
            this.telCli_txt.AnimationSpeed = 200;
            this.telCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.telCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.telCli_txt.AutoSizeHeight = false;
            this.telCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.telCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("telCli_txt.BackgroundImage")));
            this.telCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.telCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.telCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.telCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.telCli_txt.BorderRadius = 1;
            this.telCli_txt.BorderThickness = 0;
            this.telCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.telCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.telCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.telCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.telCli_txt.DefaultText = "";
            this.telCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.telCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.telCli_txt.HideSelection = true;
            this.telCli_txt.IconLeft = null;
            this.telCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.telCli_txt.IconPadding = 10;
            this.telCli_txt.IconRight = null;
            this.telCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.telCli_txt.Lines = new string[0];
            this.telCli_txt.Location = new System.Drawing.Point(13, 339);
            this.telCli_txt.MaxLength = 32767;
            this.telCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.telCli_txt.Modified = false;
            this.telCli_txt.Multiline = true;
            this.telCli_txt.Name = "telCli_txt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telCli_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.telCli_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telCli_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties20.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties20.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telCli_txt.OnIdleState = stateProperties20;
            this.telCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.telCli_txt.PasswordChar = '\0';
            this.telCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.telCli_txt.PlaceholderText = "11-93928-2007";
            this.telCli_txt.ReadOnly = false;
            this.telCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.telCli_txt.SelectedText = "";
            this.telCli_txt.SelectionLength = 0;
            this.telCli_txt.SelectionStart = 0;
            this.telCli_txt.ShortcutsEnabled = true;
            this.telCli_txt.Size = new System.Drawing.Size(349, 29);
            this.telCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.telCli_txt.TabIndex = 24;
            this.telCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.telCli_txt.TextMarginBottom = 0;
            this.telCli_txt.TextMarginLeft = 3;
            this.telCli_txt.TextMarginTop = 0;
            this.telCli_txt.TextPlaceholder = "11-93928-2007";
            this.telCli_txt.UseSystemPasswordChar = false;
            this.telCli_txt.WordWrap = true;
            // 
            // estadoCli_txt
            // 
            this.estadoCli_txt.AcceptsReturn = false;
            this.estadoCli_txt.AcceptsTab = false;
            this.estadoCli_txt.AnimationSpeed = 200;
            this.estadoCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.estadoCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.estadoCli_txt.AutoSizeHeight = false;
            this.estadoCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.estadoCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("estadoCli_txt.BackgroundImage")));
            this.estadoCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.estadoCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.estadoCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.estadoCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.estadoCli_txt.BorderRadius = 1;
            this.estadoCli_txt.BorderThickness = 0;
            this.estadoCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.estadoCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.estadoCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.estadoCli_txt.DefaultText = "";
            this.estadoCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.estadoCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.estadoCli_txt.HideSelection = true;
            this.estadoCli_txt.IconLeft = null;
            this.estadoCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoCli_txt.IconPadding = 10;
            this.estadoCli_txt.IconRight = null;
            this.estadoCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoCli_txt.Lines = new string[0];
            this.estadoCli_txt.Location = new System.Drawing.Point(412, 261);
            this.estadoCli_txt.MaxLength = 32767;
            this.estadoCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.estadoCli_txt.Modified = false;
            this.estadoCli_txt.Multiline = true;
            this.estadoCli_txt.Name = "estadoCli_txt";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoCli_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.estadoCli_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoCli_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties24.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties24.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoCli_txt.OnIdleState = stateProperties24;
            this.estadoCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.estadoCli_txt.PasswordChar = '\0';
            this.estadoCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.estadoCli_txt.PlaceholderText = "Sao Paulo";
            this.estadoCli_txt.ReadOnly = false;
            this.estadoCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.estadoCli_txt.SelectedText = "";
            this.estadoCli_txt.SelectionLength = 0;
            this.estadoCli_txt.SelectionStart = 0;
            this.estadoCli_txt.ShortcutsEnabled = true;
            this.estadoCli_txt.Size = new System.Drawing.Size(349, 29);
            this.estadoCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.estadoCli_txt.TabIndex = 22;
            this.estadoCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.estadoCli_txt.TextMarginBottom = 0;
            this.estadoCli_txt.TextMarginLeft = 3;
            this.estadoCli_txt.TextMarginTop = 0;
            this.estadoCli_txt.TextPlaceholder = "Sao Paulo";
            this.estadoCli_txt.UseSystemPasswordChar = false;
            this.estadoCli_txt.WordWrap = true;
            // 
            // cpfCli_txt
            // 
            this.cpfCli_txt.AcceptsReturn = false;
            this.cpfCli_txt.AcceptsTab = false;
            this.cpfCli_txt.AnimationSpeed = 200;
            this.cpfCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cpfCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cpfCli_txt.AutoSizeHeight = false;
            this.cpfCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.cpfCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cpfCli_txt.BackgroundImage")));
            this.cpfCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cpfCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cpfCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cpfCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.cpfCli_txt.BorderRadius = 1;
            this.cpfCli_txt.BorderThickness = 0;
            this.cpfCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cpfCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cpfCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cpfCli_txt.DefaultText = "";
            this.cpfCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.cpfCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.cpfCli_txt.HideSelection = true;
            this.cpfCli_txt.IconLeft = null;
            this.cpfCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfCli_txt.IconPadding = 10;
            this.cpfCli_txt.IconRight = null;
            this.cpfCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfCli_txt.Lines = new string[0];
            this.cpfCli_txt.Location = new System.Drawing.Point(12, 262);
            this.cpfCli_txt.MaxLength = 32767;
            this.cpfCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cpfCli_txt.Modified = false;
            this.cpfCli_txt.Multiline = true;
            this.cpfCli_txt.Name = "cpfCli_txt";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfCli_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cpfCli_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfCli_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties28.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties28.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfCli_txt.OnIdleState = stateProperties28;
            this.cpfCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.cpfCli_txt.PasswordChar = '\0';
            this.cpfCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cpfCli_txt.PlaceholderText = "111-111-111-11";
            this.cpfCli_txt.ReadOnly = false;
            this.cpfCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cpfCli_txt.SelectedText = "";
            this.cpfCli_txt.SelectionLength = 0;
            this.cpfCli_txt.SelectionStart = 0;
            this.cpfCli_txt.ShortcutsEnabled = true;
            this.cpfCli_txt.Size = new System.Drawing.Size(349, 29);
            this.cpfCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cpfCli_txt.TabIndex = 20;
            this.cpfCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.cpfCli_txt.TextMarginBottom = 0;
            this.cpfCli_txt.TextMarginLeft = 3;
            this.cpfCli_txt.TextMarginTop = 0;
            this.cpfCli_txt.TextPlaceholder = "111-111-111-11";
            this.cpfCli_txt.UseSystemPasswordChar = false;
            this.cpfCli_txt.WordWrap = true;
            this.cpfCli_txt.TextChanged += new System.EventHandler(this.marcaProd_txt_TextChanged);
            // 
            // rgcli_txt
            // 
            this.rgcli_txt.AcceptsReturn = false;
            this.rgcli_txt.AcceptsTab = false;
            this.rgcli_txt.AnimationSpeed = 200;
            this.rgcli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rgcli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rgcli_txt.AutoSizeHeight = false;
            this.rgcli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.rgcli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rgcli_txt.BackgroundImage")));
            this.rgcli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rgcli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rgcli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rgcli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.rgcli_txt.BorderRadius = 1;
            this.rgcli_txt.BorderThickness = 0;
            this.rgcli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.rgcli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rgcli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rgcli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rgcli_txt.DefaultText = "";
            this.rgcli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.rgcli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.rgcli_txt.HideSelection = true;
            this.rgcli_txt.IconLeft = null;
            this.rgcli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rgcli_txt.IconPadding = 10;
            this.rgcli_txt.IconRight = null;
            this.rgcli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rgcli_txt.Lines = new string[0];
            this.rgcli_txt.Location = new System.Drawing.Point(12, 184);
            this.rgcli_txt.MaxLength = 32767;
            this.rgcli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.rgcli_txt.Modified = false;
            this.rgcli_txt.Multiline = true;
            this.rgcli_txt.Name = "rgcli_txt";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rgcli_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rgcli_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rgcli_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties32.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties32.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rgcli_txt.OnIdleState = stateProperties32;
            this.rgcli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.rgcli_txt.PasswordChar = '\0';
            this.rgcli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rgcli_txt.PlaceholderText = "111.111.11.1";
            this.rgcli_txt.ReadOnly = false;
            this.rgcli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rgcli_txt.SelectedText = "";
            this.rgcli_txt.SelectionLength = 0;
            this.rgcli_txt.SelectionStart = 0;
            this.rgcli_txt.ShortcutsEnabled = true;
            this.rgcli_txt.Size = new System.Drawing.Size(349, 29);
            this.rgcli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.rgcli_txt.TabIndex = 18;
            this.rgcli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.rgcli_txt.TextMarginBottom = 0;
            this.rgcli_txt.TextMarginLeft = 3;
            this.rgcli_txt.TextMarginTop = 0;
            this.rgcli_txt.TextPlaceholder = "111.111.11.1";
            this.rgcli_txt.UseSystemPasswordChar = false;
            this.rgcli_txt.WordWrap = true;
            // 
            // idCliente_txt
            // 
            this.idCliente_txt.AcceptsReturn = false;
            this.idCliente_txt.AcceptsTab = false;
            this.idCliente_txt.AnimationSpeed = 200;
            this.idCliente_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idCliente_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idCliente_txt.AutoSizeHeight = false;
            this.idCliente_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.idCliente_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idCliente_txt.BackgroundImage")));
            this.idCliente_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idCliente_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idCliente_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idCliente_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.idCliente_txt.BorderRadius = 1;
            this.idCliente_txt.BorderThickness = 0;
            this.idCliente_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idCliente_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idCliente_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idCliente_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idCliente_txt.DefaultText = "";
            this.idCliente_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.idCliente_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.idCliente_txt.HideSelection = true;
            this.idCliente_txt.IconLeft = null;
            this.idCliente_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idCliente_txt.IconPadding = 10;
            this.idCliente_txt.IconRight = null;
            this.idCliente_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idCliente_txt.Lines = new string[0];
            this.idCliente_txt.Location = new System.Drawing.Point(13, 43);
            this.idCliente_txt.MaxLength = 32767;
            this.idCliente_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idCliente_txt.Modified = false;
            this.idCliente_txt.Multiline = true;
            this.idCliente_txt.Name = "idCliente_txt";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCliente_txt.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idCliente_txt.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCliente_txt.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties36.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties36.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCliente_txt.OnIdleState = stateProperties36;
            this.idCliente_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idCliente_txt.PasswordChar = '\0';
            this.idCliente_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idCliente_txt.PlaceholderText = "Cliente";
            this.idCliente_txt.ReadOnly = true;
            this.idCliente_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idCliente_txt.SelectedText = "";
            this.idCliente_txt.SelectionLength = 0;
            this.idCliente_txt.SelectionStart = 0;
            this.idCliente_txt.ShortcutsEnabled = true;
            this.idCliente_txt.Size = new System.Drawing.Size(110, 26);
            this.idCliente_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idCliente_txt.TabIndex = 16;
            this.idCliente_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.idCliente_txt.TextMarginBottom = 0;
            this.idCliente_txt.TextMarginLeft = 3;
            this.idCliente_txt.TextMarginTop = 0;
            this.idCliente_txt.TextPlaceholder = "Cliente";
            this.idCliente_txt.UseSystemPasswordChar = false;
            this.idCliente_txt.WordWrap = true;
            // 
            // add_btn
            // 
            this.add_btn.AllowAnimations = true;
            this.add_btn.AllowMouseEffects = true;
            this.add_btn.AllowToggling = false;
            this.add_btn.AnimationSpeed = 200;
            this.add_btn.AutoGenerateColors = false;
            this.add_btn.AutoRoundBorders = false;
            this.add_btn.AutoSizeLeftIcon = true;
            this.add_btn.AutoSizeRightIcon = true;
            this.add_btn.BackColor = System.Drawing.Color.Transparent;
            this.add_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("add_btn.BackgroundImage")));
            this.add_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.ButtonText = "Editar";
            this.add_btn.ButtonTextMarginLeft = 0;
            this.add_btn.ColorContrastOnClick = 45;
            this.add_btn.ColorContrastOnHover = 45;
            this.add_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.add_btn.CustomizableEdges = borderEdges1;
            this.add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.add_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.add_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.add_btn.Font = new System.Drawing.Font("Raleway", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.add_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.add_btn.IconLeft = null;
            this.add_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.add_btn.IconMarginLeft = 11;
            this.add_btn.IconPadding = 10;
            this.add_btn.IconRight = null;
            this.add_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.add_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.add_btn.IconSize = 25;
            this.add_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.add_btn.IdleBorderRadius = 0;
            this.add_btn.IdleBorderThickness = 0;
            this.add_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.add_btn.IdleIconLeftImage = null;
            this.add_btn.IdleIconRightImage = null;
            this.add_btn.IndicateFocus = false;
            this.add_btn.Location = new System.Drawing.Point(288, 400);
            this.add_btn.Name = "add_btn";
            this.add_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.OnDisabledState.BorderRadius = 1;
            this.add_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnDisabledState.BorderThickness = 1;
            this.add_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.add_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.add_btn.OnDisabledState.IconLeftImage = null;
            this.add_btn.OnDisabledState.IconRightImage = null;
            this.add_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.BorderRadius = 1;
            this.add_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.onHoverState.BorderThickness = 1;
            this.add_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.add_btn.onHoverState.IconLeftImage = null;
            this.add_btn.onHoverState.IconRightImage = null;
            this.add_btn.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.add_btn.OnIdleState.BorderRadius = 1;
            this.add_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnIdleState.BorderThickness = 1;
            this.add_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.add_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.add_btn.OnIdleState.IconLeftImage = null;
            this.add_btn.OnIdleState.IconRightImage = null;
            this.add_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.BorderRadius = 1;
            this.add_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnPressedState.BorderThickness = 1;
            this.add_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.add_btn.OnPressedState.IconLeftImage = null;
            this.add_btn.OnPressedState.IconRightImage = null;
            this.add_btn.Size = new System.Drawing.Size(227, 50);
            this.add_btn.TabIndex = 0;
            this.add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.add_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.add_btn.TextMarginLeft = 0;
            this.add_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.add_btn.UseDefaultRadiusAndThickness = true;
            this.add_btn.Click += new System.EventHandler(this.add_btn_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel8.Location = new System.Drawing.Point(412, 311);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(47, 22);
            this.bunifuLabel8.TabIndex = 35;
            this.bunifuLabel8.Text = "Email:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // emailCli_txt
            // 
            this.emailCli_txt.AcceptsReturn = false;
            this.emailCli_txt.AcceptsTab = false;
            this.emailCli_txt.AnimationSpeed = 200;
            this.emailCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailCli_txt.AutoSizeHeight = false;
            this.emailCli_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.emailCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailCli_txt.BackgroundImage")));
            this.emailCli_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.emailCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.emailCli_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.emailCli_txt.BorderRadius = 1;
            this.emailCli_txt.BorderThickness = 0;
            this.emailCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.emailCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailCli_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailCli_txt.DefaultText = "";
            this.emailCli_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.emailCli_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.emailCli_txt.HideSelection = true;
            this.emailCli_txt.IconLeft = null;
            this.emailCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailCli_txt.IconPadding = 10;
            this.emailCli_txt.IconRight = null;
            this.emailCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailCli_txt.Lines = new string[0];
            this.emailCli_txt.Location = new System.Drawing.Point(412, 339);
            this.emailCli_txt.MaxLength = 32767;
            this.emailCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailCli_txt.Modified = false;
            this.emailCli_txt.Multiline = true;
            this.emailCli_txt.Name = "emailCli_txt";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailCli_txt.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailCli_txt.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailCli_txt.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties40.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties40.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailCli_txt.OnIdleState = stateProperties40;
            this.emailCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.emailCli_txt.PasswordChar = '\0';
            this.emailCli_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailCli_txt.PlaceholderText = "ronaldinho@baiano.com";
            this.emailCli_txt.ReadOnly = false;
            this.emailCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailCli_txt.SelectedText = "";
            this.emailCli_txt.SelectionLength = 0;
            this.emailCli_txt.SelectionStart = 0;
            this.emailCli_txt.ShortcutsEnabled = true;
            this.emailCli_txt.Size = new System.Drawing.Size(349, 29);
            this.emailCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailCli_txt.TabIndex = 34;
            this.emailCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.emailCli_txt.TextMarginBottom = 0;
            this.emailCli_txt.TextMarginLeft = 3;
            this.emailCli_txt.TextMarginTop = 0;
            this.emailCli_txt.TextPlaceholder = "ronaldinho@baiano.com";
            this.emailCli_txt.UseSystemPasswordChar = false;
            this.emailCli_txt.WordWrap = true;
            // 
            // EditarClientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(800, 471);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.emailCli_txt);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bairroCli_txt);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.cidadeCli_txt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.nomeCli_txt);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.ruaCli_txt);
            this.Controls.Add(this.label);
            this.Controls.Add(this.telCli_txt);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.estadoCli_txt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.cpfCli_txt);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.rgcli_txt);
            this.Controls.Add(this.idCliente_label);
            this.Controls.Add(this.idCliente_txt);
            this.Controls.Add(this.add_btn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "EditarClientes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AdicionarProdutos";
            this.Load += new System.EventHandler(this.EditarClientes_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton add_btn;
        private Bunifu.UI.WinForms.BunifuTextBox idCliente_txt;
        private Bunifu.UI.WinForms.BunifuLabel idCliente_label;
        private Bunifu.UI.WinForms.BunifuTextBox rgcli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox cpfCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox estadoCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel label;
        private Bunifu.UI.WinForms.BunifuTextBox telCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox ruaCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox nomeCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox cidadeCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox bairroCli_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox emailCli_txt;
    }
}