namespace ProjetoJeffersonADM
{
    partial class AdicionarPedido
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdicionarPedido));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.idProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pagamento_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.parcelas_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.quantidade_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.login_button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.idCli_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dataPedido_txt = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.idFabricante_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nome = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Archivo Black", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(409, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(391, 60);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Adicionar Pedidos";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel1.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(141, 112);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(102, 25);
            this.bunifuLabel4.TabIndex = 22;
            this.bunifuLabel4.Text = "Id do produto:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel4.UseGdiPlusTextRendering = true;
            // 
            // idProd_txt
            // 
            this.idProd_txt.AcceptsReturn = false;
            this.idProd_txt.AcceptsTab = false;
            this.idProd_txt.AnimationSpeed = 200;
            this.idProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idProd_txt.AutoSizeHeight = true;
            this.idProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idProd_txt.BackgroundImage")));
            this.idProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.idProd_txt.BorderRadius = 16;
            this.idProd_txt.BorderThickness = 1;
            this.idProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idProd_txt.DefaultText = "";
            this.idProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idProd_txt.ForeColor = System.Drawing.Color.White;
            this.idProd_txt.HideSelection = true;
            this.idProd_txt.IconLeft = null;
            this.idProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.IconPadding = 10;
            this.idProd_txt.IconRight = null;
            this.idProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.Lines = new string[0];
            this.idProd_txt.Location = new System.Drawing.Point(139, 143);
            this.idProd_txt.MaxLength = 32767;
            this.idProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idProd_txt.Modified = false;
            this.idProd_txt.Multiline = true;
            this.idProd_txt.Name = "idProd_txt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idProd_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnIdleState = stateProperties4;
            this.idProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idProd_txt.PasswordChar = '\0';
            this.idProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.idProd_txt.PlaceholderText = "ID";
            this.idProd_txt.ReadOnly = false;
            this.idProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idProd_txt.SelectedText = "";
            this.idProd_txt.SelectionLength = 0;
            this.idProd_txt.SelectionStart = 0;
            this.idProd_txt.ShortcutsEnabled = true;
            this.idProd_txt.Size = new System.Drawing.Size(135, 59);
            this.idProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idProd_txt.TabIndex = 21;
            this.idProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idProd_txt.TextMarginBottom = 0;
            this.idProd_txt.TextMarginLeft = 3;
            this.idProd_txt.TextMarginTop = 12;
            this.idProd_txt.TextPlaceholder = "ID";
            this.idProd_txt.UseSystemPasswordChar = false;
            this.idProd_txt.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(139, 234);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(115, 25);
            this.bunifuLabel2.TabIndex = 24;
            this.bunifuLabel2.Text = "Data do pedido:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel2.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(139, 357);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(161, 25);
            this.bunifuLabel3.TabIndex = 26;
            this.bunifuLabel3.Text = "Forma de pagamento:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel3.UseGdiPlusTextRendering = true;
            // 
            // pagamento_txt
            // 
            this.pagamento_txt.AcceptsReturn = false;
            this.pagamento_txt.AcceptsTab = false;
            this.pagamento_txt.AnimationSpeed = 200;
            this.pagamento_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.pagamento_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.pagamento_txt.AutoSizeHeight = true;
            this.pagamento_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.pagamento_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pagamento_txt.BackgroundImage")));
            this.pagamento_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pagamento_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pagamento_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pagamento_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.pagamento_txt.BorderRadius = 16;
            this.pagamento_txt.BorderThickness = 1;
            this.pagamento_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.pagamento_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.pagamento_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.pagamento_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pagamento_txt.DefaultText = "";
            this.pagamento_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.pagamento_txt.ForeColor = System.Drawing.Color.White;
            this.pagamento_txt.HideSelection = true;
            this.pagamento_txt.IconLeft = null;
            this.pagamento_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.pagamento_txt.IconPadding = 10;
            this.pagamento_txt.IconRight = null;
            this.pagamento_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.pagamento_txt.Lines = new string[0];
            this.pagamento_txt.Location = new System.Drawing.Point(137, 388);
            this.pagamento_txt.MaxLength = 32767;
            this.pagamento_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.pagamento_txt.Modified = false;
            this.pagamento_txt.Multiline = true;
            this.pagamento_txt.Name = "pagamento_txt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pagamento_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.pagamento_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pagamento_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pagamento_txt.OnIdleState = stateProperties8;
            this.pagamento_txt.Padding = new System.Windows.Forms.Padding(3);
            this.pagamento_txt.PasswordChar = '\0';
            this.pagamento_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.pagamento_txt.PlaceholderText = "Digite a forma de pagamento:";
            this.pagamento_txt.ReadOnly = false;
            this.pagamento_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.pagamento_txt.SelectedText = "";
            this.pagamento_txt.SelectionLength = 0;
            this.pagamento_txt.SelectionStart = 0;
            this.pagamento_txt.ShortcutsEnabled = true;
            this.pagamento_txt.Size = new System.Drawing.Size(419, 59);
            this.pagamento_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.pagamento_txt.TabIndex = 25;
            this.pagamento_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.pagamento_txt.TextMarginBottom = 0;
            this.pagamento_txt.TextMarginLeft = 3;
            this.pagamento_txt.TextMarginTop = 12;
            this.pagamento_txt.TextPlaceholder = "Digite a forma de pagamento:";
            this.pagamento_txt.UseSystemPasswordChar = false;
            this.pagamento_txt.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(644, 234);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(109, 25);
            this.bunifuLabel5.TabIndex = 28;
            this.bunifuLabel5.Text = "Parcelamento:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel5.UseGdiPlusTextRendering = true;
            // 
            // parcelas_txt
            // 
            this.parcelas_txt.AcceptsReturn = false;
            this.parcelas_txt.AcceptsTab = false;
            this.parcelas_txt.AnimationSpeed = 200;
            this.parcelas_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.parcelas_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.parcelas_txt.AutoSizeHeight = true;
            this.parcelas_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.parcelas_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("parcelas_txt.BackgroundImage")));
            this.parcelas_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.parcelas_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.parcelas_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.parcelas_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.parcelas_txt.BorderRadius = 16;
            this.parcelas_txt.BorderThickness = 1;
            this.parcelas_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.parcelas_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.parcelas_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.parcelas_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.parcelas_txt.DefaultText = "";
            this.parcelas_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.parcelas_txt.ForeColor = System.Drawing.Color.White;
            this.parcelas_txt.HideSelection = true;
            this.parcelas_txt.IconLeft = null;
            this.parcelas_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.parcelas_txt.IconPadding = 10;
            this.parcelas_txt.IconRight = null;
            this.parcelas_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.parcelas_txt.Lines = new string[0];
            this.parcelas_txt.Location = new System.Drawing.Point(642, 265);
            this.parcelas_txt.MaxLength = 32767;
            this.parcelas_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.parcelas_txt.Modified = false;
            this.parcelas_txt.Multiline = true;
            this.parcelas_txt.Name = "parcelas_txt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.parcelas_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.parcelas_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.parcelas_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.parcelas_txt.OnIdleState = stateProperties12;
            this.parcelas_txt.Padding = new System.Windows.Forms.Padding(3);
            this.parcelas_txt.PasswordChar = '\0';
            this.parcelas_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.parcelas_txt.PlaceholderText = "Digite o parcelamento do produto";
            this.parcelas_txt.ReadOnly = false;
            this.parcelas_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.parcelas_txt.SelectedText = "";
            this.parcelas_txt.SelectionLength = 0;
            this.parcelas_txt.SelectionStart = 0;
            this.parcelas_txt.ShortcutsEnabled = true;
            this.parcelas_txt.Size = new System.Drawing.Size(419, 59);
            this.parcelas_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.parcelas_txt.TabIndex = 27;
            this.parcelas_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.parcelas_txt.TextMarginBottom = 0;
            this.parcelas_txt.TextMarginLeft = 3;
            this.parcelas_txt.TextMarginTop = 12;
            this.parcelas_txt.TextPlaceholder = "Digite o parcelamento do produto";
            this.parcelas_txt.UseSystemPasswordChar = false;
            this.parcelas_txt.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(648, 357);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(90, 25);
            this.bunifuLabel6.TabIndex = 30;
            this.bunifuLabel6.Text = "Quantidade:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel6.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel6.UseGdiPlusTextRendering = true;
            // 
            // quantidade_txt
            // 
            this.quantidade_txt.AcceptsReturn = false;
            this.quantidade_txt.AcceptsTab = false;
            this.quantidade_txt.AnimationSpeed = 200;
            this.quantidade_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.quantidade_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.quantidade_txt.AutoSizeHeight = true;
            this.quantidade_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.quantidade_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("quantidade_txt.BackgroundImage")));
            this.quantidade_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.quantidade_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.quantidade_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.quantidade_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.quantidade_txt.BorderRadius = 16;
            this.quantidade_txt.BorderThickness = 1;
            this.quantidade_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.quantidade_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.quantidade_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.quantidade_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.quantidade_txt.DefaultText = "";
            this.quantidade_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.quantidade_txt.ForeColor = System.Drawing.Color.White;
            this.quantidade_txt.HideSelection = true;
            this.quantidade_txt.IconLeft = null;
            this.quantidade_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.quantidade_txt.IconPadding = 10;
            this.quantidade_txt.IconRight = null;
            this.quantidade_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.quantidade_txt.Lines = new string[0];
            this.quantidade_txt.Location = new System.Drawing.Point(646, 388);
            this.quantidade_txt.MaxLength = 32767;
            this.quantidade_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.quantidade_txt.Modified = false;
            this.quantidade_txt.Multiline = true;
            this.quantidade_txt.Name = "quantidade_txt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantidade_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.quantidade_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantidade_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantidade_txt.OnIdleState = stateProperties16;
            this.quantidade_txt.Padding = new System.Windows.Forms.Padding(3);
            this.quantidade_txt.PasswordChar = '\0';
            this.quantidade_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.quantidade_txt.PlaceholderText = "Digite a quantidade que o cliente vai comprar";
            this.quantidade_txt.ReadOnly = false;
            this.quantidade_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.quantidade_txt.SelectedText = "";
            this.quantidade_txt.SelectionLength = 0;
            this.quantidade_txt.SelectionStart = 0;
            this.quantidade_txt.ShortcutsEnabled = true;
            this.quantidade_txt.Size = new System.Drawing.Size(419, 59);
            this.quantidade_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.quantidade_txt.TabIndex = 29;
            this.quantidade_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.quantidade_txt.TextMarginBottom = 0;
            this.quantidade_txt.TextMarginLeft = 3;
            this.quantidade_txt.TextMarginTop = 12;
            this.quantidade_txt.TextPlaceholder = "Digite a quantidade que o cliente vai comprar";
            this.quantidade_txt.UseSystemPasswordChar = false;
            this.quantidade_txt.WordWrap = true;
            // 
            // login_button
            // 
            this.login_button.AllowAnimations = true;
            this.login_button.AllowMouseEffects = true;
            this.login_button.AllowToggling = false;
            this.login_button.AnimationSpeed = 200;
            this.login_button.AutoGenerateColors = false;
            this.login_button.AutoRoundBorders = false;
            this.login_button.AutoSizeLeftIcon = true;
            this.login_button.AutoSizeRightIcon = true;
            this.login_button.BackColor = System.Drawing.Color.Transparent;
            this.login_button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("login_button.BackgroundImage")));
            this.login_button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.ButtonText = "Adicionar";
            this.login_button.ButtonTextMarginLeft = 0;
            this.login_button.ColorContrastOnClick = 45;
            this.login_button.ColorContrastOnHover = 45;
            this.login_button.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.login_button.CustomizableEdges = borderEdges1;
            this.login_button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.login_button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.login_button.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.login_button.ForeColor = System.Drawing.Color.White;
            this.login_button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.login_button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.login_button.IconMarginLeft = 11;
            this.login_button.IconPadding = 10;
            this.login_button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.login_button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.login_button.IconSize = 25;
            this.login_button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleBorderRadius = 10;
            this.login_button.IdleBorderThickness = 1;
            this.login_button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleIconLeftImage = null;
            this.login_button.IdleIconRightImage = null;
            this.login_button.IndicateFocus = false;
            this.login_button.Location = new System.Drawing.Point(642, 582);
            this.login_button.Name = "login_button";
            this.login_button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.OnDisabledState.BorderRadius = 10;
            this.login_button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnDisabledState.BorderThickness = 1;
            this.login_button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.OnDisabledState.IconLeftImage = null;
            this.login_button.OnDisabledState.IconRightImage = null;
            this.login_button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.BorderRadius = 10;
            this.login_button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.onHoverState.BorderThickness = 1;
            this.login_button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.login_button.onHoverState.IconLeftImage = null;
            this.login_button.onHoverState.IconRightImage = null;
            this.login_button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.BorderRadius = 10;
            this.login_button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnIdleState.BorderThickness = 1;
            this.login_button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnIdleState.IconLeftImage = null;
            this.login_button.OnIdleState.IconRightImage = null;
            this.login_button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.BorderRadius = 10;
            this.login_button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnPressedState.BorderThickness = 1;
            this.login_button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnPressedState.IconLeftImage = null;
            this.login_button.OnPressedState.IconRightImage = null;
            this.login_button.Size = new System.Drawing.Size(137, 39);
            this.login_button.TabIndex = 33;
            this.login_button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.login_button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.login_button.TextMarginLeft = 0;
            this.login_button.TextPadding = new System.Windows.Forms.Padding(0);
            this.login_button.UseDefaultRadiusAndThickness = true;
            this.login_button.Click += new System.EventHandler(this.login_button_Click);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Cancelar";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges2;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.bunifuButton21.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.IdleBorderRadius = 10;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(419, 582);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 10;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.BorderRadius = 10;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 10;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 10;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(137, 39);
            this.bunifuButton21.TabIndex = 34;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.pictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox1.Image = global::ProjetoJeffersonADM.Properties.Resources.icons8_close_50;
            this.pictureBox1.Location = new System.Drawing.Point(1074, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pictureBox1.TabIndex = 37;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel9.Location = new System.Drawing.Point(642, 112);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(93, 25);
            this.bunifuLabel9.TabIndex = 39;
            this.bunifuLabel9.Text = "Id do cliente:";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel9.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel9.UseGdiPlusTextRendering = true;
            // 
            // idCli_txt
            // 
            this.idCli_txt.AcceptsReturn = false;
            this.idCli_txt.AcceptsTab = false;
            this.idCli_txt.AnimationSpeed = 200;
            this.idCli_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idCli_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idCli_txt.AutoSizeHeight = true;
            this.idCli_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idCli_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idCli_txt.BackgroundImage")));
            this.idCli_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idCli_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idCli_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idCli_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.idCli_txt.BorderRadius = 16;
            this.idCli_txt.BorderThickness = 1;
            this.idCli_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idCli_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idCli_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idCli_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idCli_txt.DefaultText = "";
            this.idCli_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idCli_txt.ForeColor = System.Drawing.Color.White;
            this.idCli_txt.HideSelection = true;
            this.idCli_txt.IconLeft = null;
            this.idCli_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idCli_txt.IconPadding = 10;
            this.idCli_txt.IconRight = null;
            this.idCli_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idCli_txt.Lines = new string[0];
            this.idCli_txt.Location = new System.Drawing.Point(642, 143);
            this.idCli_txt.MaxLength = 32767;
            this.idCli_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idCli_txt.Modified = false;
            this.idCli_txt.Multiline = true;
            this.idCli_txt.Name = "idCli_txt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCli_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idCli_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCli_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idCli_txt.OnIdleState = stateProperties20;
            this.idCli_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idCli_txt.PasswordChar = '\0';
            this.idCli_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.idCli_txt.PlaceholderText = "ID";
            this.idCli_txt.ReadOnly = false;
            this.idCli_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idCli_txt.SelectedText = "";
            this.idCli_txt.SelectionLength = 0;
            this.idCli_txt.SelectionStart = 0;
            this.idCli_txt.ShortcutsEnabled = true;
            this.idCli_txt.Size = new System.Drawing.Size(135, 59);
            this.idCli_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idCli_txt.TabIndex = 38;
            this.idCli_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idCli_txt.TextMarginBottom = 0;
            this.idCli_txt.TextMarginLeft = 3;
            this.idCli_txt.TextMarginTop = 12;
            this.idCli_txt.TextPlaceholder = "ID";
            this.idCli_txt.UseSystemPasswordChar = false;
            this.idCli_txt.WordWrap = true;
            // 
            // dataPedido_txt
            // 
            this.dataPedido_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.dataPedido_txt.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.dataPedido_txt.BorderRadius = 8;
            this.dataPedido_txt.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.Color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.dataPedido_txt.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.dataPedido_txt.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dataPedido_txt.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.dataPedido_txt.DisplayWeekNumbers = false;
            this.dataPedido_txt.DPHeight = 0;
            this.dataPedido_txt.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dataPedido_txt.FillDatePicker = false;
            this.dataPedido_txt.Font = new System.Drawing.Font("Archivo", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dataPedido_txt.ForeColor = System.Drawing.Color.White;
            this.dataPedido_txt.Icon = ((System.Drawing.Image)(resources.GetObject("dataPedido_txt.Icon")));
            this.dataPedido_txt.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.dataPedido_txt.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dataPedido_txt.LeftTextMargin = 5;
            this.dataPedido_txt.Location = new System.Drawing.Point(139, 265);
            this.dataPedido_txt.MinimumSize = new System.Drawing.Size(4, 32);
            this.dataPedido_txt.Name = "dataPedido_txt";
            this.dataPedido_txt.Size = new System.Drawing.Size(290, 32);
            this.dataPedido_txt.TabIndex = 40;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(362, 112);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(118, 25);
            this.bunifuLabel7.TabIndex = 42;
            this.bunifuLabel7.Text = "Id do fabricante:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel7.UseGdiPlusTextRendering = true;
            this.bunifuLabel7.Click += new System.EventHandler(this.bunifuLabel7_Click);
            // 
            // idFabricante_txt
            // 
            this.idFabricante_txt.AcceptsReturn = false;
            this.idFabricante_txt.AcceptsTab = false;
            this.idFabricante_txt.AnimationSpeed = 200;
            this.idFabricante_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idFabricante_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idFabricante_txt.AutoSizeHeight = true;
            this.idFabricante_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idFabricante_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idFabricante_txt.BackgroundImage")));
            this.idFabricante_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idFabricante_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idFabricante_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idFabricante_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.idFabricante_txt.BorderRadius = 16;
            this.idFabricante_txt.BorderThickness = 1;
            this.idFabricante_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idFabricante_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idFabricante_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idFabricante_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idFabricante_txt.DefaultText = "";
            this.idFabricante_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idFabricante_txt.ForeColor = System.Drawing.Color.White;
            this.idFabricante_txt.HideSelection = true;
            this.idFabricante_txt.IconLeft = null;
            this.idFabricante_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idFabricante_txt.IconPadding = 10;
            this.idFabricante_txt.IconRight = null;
            this.idFabricante_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idFabricante_txt.Lines = new string[0];
            this.idFabricante_txt.Location = new System.Drawing.Point(360, 143);
            this.idFabricante_txt.MaxLength = 32767;
            this.idFabricante_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idFabricante_txt.Modified = false;
            this.idFabricante_txt.Multiline = true;
            this.idFabricante_txt.Name = "idFabricante_txt";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idFabricante_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idFabricante_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idFabricante_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idFabricante_txt.OnIdleState = stateProperties24;
            this.idFabricante_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idFabricante_txt.PasswordChar = '\0';
            this.idFabricante_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.idFabricante_txt.PlaceholderText = "ID";
            this.idFabricante_txt.ReadOnly = false;
            this.idFabricante_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idFabricante_txt.SelectedText = "";
            this.idFabricante_txt.SelectionLength = 0;
            this.idFabricante_txt.SelectionStart = 0;
            this.idFabricante_txt.ShortcutsEnabled = true;
            this.idFabricante_txt.Size = new System.Drawing.Size(135, 59);
            this.idFabricante_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idFabricante_txt.TabIndex = 41;
            this.idFabricante_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idFabricante_txt.TextMarginBottom = 0;
            this.idFabricante_txt.TextMarginLeft = 3;
            this.idFabricante_txt.TextMarginTop = 12;
            this.idFabricante_txt.TextPlaceholder = "ID";
            this.idFabricante_txt.UseSystemPasswordChar = false;
            this.idFabricante_txt.WordWrap = true;
            this.idFabricante_txt.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // nome
            // 
            this.nome.AllowDragging = false;
            this.nome.AllowMultipleViews = true;
            this.nome.ClickToClose = true;
            this.nome.DoubleClickToClose = true;
            this.nome.DurationAfterIdle = 3000;
            this.nome.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.nome.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.nome.ErrorOptions.ActionBorderRadius = 1;
            this.nome.ErrorOptions.ActionFont = new System.Drawing.Font("Archivo Medium", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nome.ErrorOptions.ActionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nome.ErrorOptions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.nome.ErrorOptions.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.nome.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nome.ErrorOptions.Font = new System.Drawing.Font("Archivo", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nome.ErrorOptions.ForeColor = System.Drawing.Color.White;
            this.nome.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.nome.ErrorOptions.IconLeftMargin = 12;
            this.nome.FadeCloseIcon = false;
            this.nome.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.nome.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.InformationOptions.ActionBorderRadius = 1;
            this.nome.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.nome.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.nome.InformationOptions.BackColor = System.Drawing.Color.White;
            this.nome.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.nome.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.nome.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.nome.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.nome.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.nome.InformationOptions.IconLeftMargin = 12;
            this.nome.Margin = 10;
            this.nome.MaximumSize = new System.Drawing.Size(0, 0);
            this.nome.MaximumViews = 7;
            this.nome.MessageRightMargin = 15;
            this.nome.MessageTopMargin = 0;
            this.nome.MinimumSize = new System.Drawing.Size(0, 0);
            this.nome.ShowBorders = false;
            this.nome.ShowCloseIcon = false;
            this.nome.ShowIcon = true;
            this.nome.ShowShadows = true;
            this.nome.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.SuccessOptions.ActionBorderRadius = 1;
            this.nome.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.nome.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.nome.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.nome.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.nome.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.nome.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.nome.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.nome.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.nome.SuccessOptions.IconLeftMargin = 12;
            this.nome.ViewsMargin = 7;
            this.nome.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.nome.WarningOptions.ActionBorderRadius = 1;
            this.nome.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.nome.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.nome.WarningOptions.BackColor = System.Drawing.Color.White;
            this.nome.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.nome.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.nome.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.nome.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.nome.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.nome.WarningOptions.IconLeftMargin = 12;
            this.nome.ZoomCloseIcon = true;
            // 
            // AdicionarPedido
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(1143, 642);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.idFabricante_txt);
            this.Controls.Add(this.dataPedido_txt);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.idCli_txt);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.login_button);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.quantidade_txt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.parcelas_txt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.pagamento_txt);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.idProd_txt);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AdicionarPedido";
            this.Text = "khjuhjk";
            this.Load += new System.EventHandler(this.AdicionarPedido_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox idProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox pagamento_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox parcelas_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox quantidade_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 login_button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox idCli_txt;
        private Bunifu.UI.WinForms.BunifuDatePicker dataPedido_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox idFabricante_txt;
        private Bunifu.UI.WinForms.BunifuSnackbar nome;
    }
}