namespace ProjetoJeffersonADM
{
    partial class EditarProdutos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditarProdutos));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.nomeProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.descriProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.marcaProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.precoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tipoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tamanhoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.login_button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.idProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Archivo Black", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(419, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(310, 60);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Editar produto";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel1.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(141, 170);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(133, 25);
            this.bunifuLabel4.TabIndex = 22;
            this.bunifuLabel4.Text = "Nome do produto:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel4.UseGdiPlusTextRendering = true;
            // 
            // nomeProd_txt
            // 
            this.nomeProd_txt.AcceptsReturn = false;
            this.nomeProd_txt.AcceptsTab = false;
            this.nomeProd_txt.AnimationSpeed = 200;
            this.nomeProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomeProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomeProd_txt.AutoSizeHeight = true;
            this.nomeProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomeProd_txt.BackgroundImage")));
            this.nomeProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.nomeProd_txt.BorderRadius = 16;
            this.nomeProd_txt.BorderThickness = 1;
            this.nomeProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomeProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomeProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomeProd_txt.DefaultText = "";
            this.nomeProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeProd_txt.ForeColor = System.Drawing.Color.White;
            this.nomeProd_txt.HideSelection = true;
            this.nomeProd_txt.IconLeft = null;
            this.nomeProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.IconPadding = 10;
            this.nomeProd_txt.IconRight = null;
            this.nomeProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.Lines = new string[0];
            this.nomeProd_txt.Location = new System.Drawing.Point(139, 201);
            this.nomeProd_txt.MaxLength = 32767;
            this.nomeProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomeProd_txt.Modified = false;
            this.nomeProd_txt.Multiline = true;
            this.nomeProd_txt.Name = "nomeProd_txt";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomeProd_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnIdleState = stateProperties32;
            this.nomeProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.nomeProd_txt.PasswordChar = '\0';
            this.nomeProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.nomeProd_txt.PlaceholderText = "Digite o nome do seu produto";
            this.nomeProd_txt.ReadOnly = false;
            this.nomeProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomeProd_txt.SelectedText = "";
            this.nomeProd_txt.SelectionLength = 0;
            this.nomeProd_txt.SelectionStart = 0;
            this.nomeProd_txt.ShortcutsEnabled = true;
            this.nomeProd_txt.Size = new System.Drawing.Size(419, 59);
            this.nomeProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomeProd_txt.TabIndex = 21;
            this.nomeProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomeProd_txt.TextMarginBottom = 0;
            this.nomeProd_txt.TextMarginLeft = 3;
            this.nomeProd_txt.TextMarginTop = 12;
            this.nomeProd_txt.TextPlaceholder = "Digite o nome do seu produto";
            this.nomeProd_txt.UseSystemPasswordChar = false;
            this.nomeProd_txt.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(143, 283);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(165, 25);
            this.bunifuLabel2.TabIndex = 24;
            this.bunifuLabel2.Text = "Descricao do produto:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel2.UseGdiPlusTextRendering = true;
            // 
            // descriProd_txt
            // 
            this.descriProd_txt.AcceptsReturn = false;
            this.descriProd_txt.AcceptsTab = false;
            this.descriProd_txt.AnimationSpeed = 200;
            this.descriProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.descriProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.descriProd_txt.AutoSizeHeight = true;
            this.descriProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.descriProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("descriProd_txt.BackgroundImage")));
            this.descriProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.descriProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.descriProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.descriProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.descriProd_txt.BorderRadius = 16;
            this.descriProd_txt.BorderThickness = 1;
            this.descriProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.descriProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.descriProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.descriProd_txt.DefaultText = "";
            this.descriProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.descriProd_txt.ForeColor = System.Drawing.Color.White;
            this.descriProd_txt.HideSelection = true;
            this.descriProd_txt.IconLeft = null;
            this.descriProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.IconPadding = 10;
            this.descriProd_txt.IconRight = null;
            this.descriProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.Lines = new string[0];
            this.descriProd_txt.Location = new System.Drawing.Point(137, 314);
            this.descriProd_txt.MaxLength = 32767;
            this.descriProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.descriProd_txt.Modified = false;
            this.descriProd_txt.Multiline = true;
            this.descriProd_txt.Name = "descriProd_txt";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.descriProd_txt.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties36.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties36.ForeColor = System.Drawing.Color.White;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnIdleState = stateProperties36;
            this.descriProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.descriProd_txt.PasswordChar = '\0';
            this.descriProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.descriProd_txt.PlaceholderText = "Digite a descricao do seu produto";
            this.descriProd_txt.ReadOnly = false;
            this.descriProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.descriProd_txt.SelectedText = "";
            this.descriProd_txt.SelectionLength = 0;
            this.descriProd_txt.SelectionStart = 0;
            this.descriProd_txt.ShortcutsEnabled = true;
            this.descriProd_txt.Size = new System.Drawing.Size(419, 59);
            this.descriProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.descriProd_txt.TabIndex = 23;
            this.descriProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.descriProd_txt.TextMarginBottom = 0;
            this.descriProd_txt.TextMarginLeft = 3;
            this.descriProd_txt.TextMarginTop = 12;
            this.descriProd_txt.TextPlaceholder = "Digite a descricao do seu produto";
            this.descriProd_txt.UseSystemPasswordChar = false;
            this.descriProd_txt.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(143, 397);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(135, 25);
            this.bunifuLabel3.TabIndex = 26;
            this.bunifuLabel3.Text = "Marca do produto:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel3.UseGdiPlusTextRendering = true;
            // 
            // marcaProd_txt
            // 
            this.marcaProd_txt.AcceptsReturn = false;
            this.marcaProd_txt.AcceptsTab = false;
            this.marcaProd_txt.AnimationSpeed = 200;
            this.marcaProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.marcaProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.marcaProd_txt.AutoSizeHeight = true;
            this.marcaProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.marcaProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("marcaProd_txt.BackgroundImage")));
            this.marcaProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.marcaProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.marcaProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.marcaProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.marcaProd_txt.BorderRadius = 16;
            this.marcaProd_txt.BorderThickness = 1;
            this.marcaProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.marcaProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.marcaProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.marcaProd_txt.DefaultText = "";
            this.marcaProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.marcaProd_txt.ForeColor = System.Drawing.Color.White;
            this.marcaProd_txt.HideSelection = true;
            this.marcaProd_txt.IconLeft = null;
            this.marcaProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.IconPadding = 10;
            this.marcaProd_txt.IconRight = null;
            this.marcaProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.Lines = new string[0];
            this.marcaProd_txt.Location = new System.Drawing.Point(141, 428);
            this.marcaProd_txt.MaxLength = 32767;
            this.marcaProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.marcaProd_txt.Modified = false;
            this.marcaProd_txt.Multiline = true;
            this.marcaProd_txt.Name = "marcaProd_txt";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.marcaProd_txt.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties40.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties40.ForeColor = System.Drawing.Color.White;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnIdleState = stateProperties40;
            this.marcaProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.marcaProd_txt.PasswordChar = '\0';
            this.marcaProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.marcaProd_txt.PlaceholderText = "Digite a marca do seu produto";
            this.marcaProd_txt.ReadOnly = false;
            this.marcaProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.marcaProd_txt.SelectedText = "";
            this.marcaProd_txt.SelectionLength = 0;
            this.marcaProd_txt.SelectionStart = 0;
            this.marcaProd_txt.ShortcutsEnabled = true;
            this.marcaProd_txt.Size = new System.Drawing.Size(419, 59);
            this.marcaProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.marcaProd_txt.TabIndex = 25;
            this.marcaProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.marcaProd_txt.TextMarginBottom = 0;
            this.marcaProd_txt.TextMarginLeft = 3;
            this.marcaProd_txt.TextMarginTop = 12;
            this.marcaProd_txt.TextPlaceholder = "Digite a marca do seu produto";
            this.marcaProd_txt.UseSystemPasswordChar = false;
            this.marcaProd_txt.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(642, 170);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(133, 25);
            this.bunifuLabel5.TabIndex = 28;
            this.bunifuLabel5.Text = "Preco do produto:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel5.UseGdiPlusTextRendering = true;
            // 
            // precoProd_txt
            // 
            this.precoProd_txt.AcceptsReturn = false;
            this.precoProd_txt.AcceptsTab = false;
            this.precoProd_txt.AnimationSpeed = 200;
            this.precoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.precoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.precoProd_txt.AutoSizeHeight = true;
            this.precoProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.precoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("precoProd_txt.BackgroundImage")));
            this.precoProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.precoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.precoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.precoProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.precoProd_txt.BorderRadius = 16;
            this.precoProd_txt.BorderThickness = 1;
            this.precoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.precoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.precoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.precoProd_txt.DefaultText = "";
            this.precoProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.precoProd_txt.ForeColor = System.Drawing.Color.White;
            this.precoProd_txt.HideSelection = true;
            this.precoProd_txt.IconLeft = null;
            this.precoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.IconPadding = 10;
            this.precoProd_txt.IconRight = null;
            this.precoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.Lines = new string[0];
            this.precoProd_txt.Location = new System.Drawing.Point(640, 201);
            this.precoProd_txt.MaxLength = 32767;
            this.precoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.precoProd_txt.Modified = false;
            this.precoProd_txt.Multiline = true;
            this.precoProd_txt.Name = "precoProd_txt";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.precoProd_txt.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties44.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties44.ForeColor = System.Drawing.Color.White;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnIdleState = stateProperties44;
            this.precoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.precoProd_txt.PasswordChar = '\0';
            this.precoProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.precoProd_txt.PlaceholderText = "Digite o preco do seu produto";
            this.precoProd_txt.ReadOnly = false;
            this.precoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.precoProd_txt.SelectedText = "";
            this.precoProd_txt.SelectionLength = 0;
            this.precoProd_txt.SelectionStart = 0;
            this.precoProd_txt.ShortcutsEnabled = true;
            this.precoProd_txt.Size = new System.Drawing.Size(419, 59);
            this.precoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.precoProd_txt.TabIndex = 27;
            this.precoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.precoProd_txt.TextMarginBottom = 0;
            this.precoProd_txt.TextMarginLeft = 3;
            this.precoProd_txt.TextMarginTop = 12;
            this.precoProd_txt.TextPlaceholder = "Digite o preco do seu produto";
            this.precoProd_txt.UseSystemPasswordChar = false;
            this.precoProd_txt.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(642, 283);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(121, 25);
            this.bunifuLabel6.TabIndex = 30;
            this.bunifuLabel6.Text = "Tipo do produto:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel6.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel6.UseGdiPlusTextRendering = true;
            // 
            // tipoProd_txt
            // 
            this.tipoProd_txt.AcceptsReturn = false;
            this.tipoProd_txt.AcceptsTab = false;
            this.tipoProd_txt.AnimationSpeed = 200;
            this.tipoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tipoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tipoProd_txt.AutoSizeHeight = true;
            this.tipoProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.tipoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tipoProd_txt.BackgroundImage")));
            this.tipoProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tipoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tipoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tipoProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tipoProd_txt.BorderRadius = 16;
            this.tipoProd_txt.BorderThickness = 1;
            this.tipoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tipoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tipoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tipoProd_txt.DefaultText = "";
            this.tipoProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.tipoProd_txt.ForeColor = System.Drawing.Color.White;
            this.tipoProd_txt.HideSelection = true;
            this.tipoProd_txt.IconLeft = null;
            this.tipoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.IconPadding = 10;
            this.tipoProd_txt.IconRight = null;
            this.tipoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.Lines = new string[0];
            this.tipoProd_txt.Location = new System.Drawing.Point(640, 314);
            this.tipoProd_txt.MaxLength = 32767;
            this.tipoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tipoProd_txt.Modified = false;
            this.tipoProd_txt.Multiline = true;
            this.tipoProd_txt.Name = "tipoProd_txt";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tipoProd_txt.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties48.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties48.ForeColor = System.Drawing.Color.White;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnIdleState = stateProperties48;
            this.tipoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tipoProd_txt.PasswordChar = '\0';
            this.tipoProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.tipoProd_txt.PlaceholderText = "Digite o tipo do seu produto";
            this.tipoProd_txt.ReadOnly = false;
            this.tipoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tipoProd_txt.SelectedText = "";
            this.tipoProd_txt.SelectionLength = 0;
            this.tipoProd_txt.SelectionStart = 0;
            this.tipoProd_txt.ShortcutsEnabled = true;
            this.tipoProd_txt.Size = new System.Drawing.Size(419, 59);
            this.tipoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tipoProd_txt.TabIndex = 29;
            this.tipoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tipoProd_txt.TextMarginBottom = 0;
            this.tipoProd_txt.TextMarginLeft = 3;
            this.tipoProd_txt.TextMarginTop = 12;
            this.tipoProd_txt.TextPlaceholder = "Digite o tipo do seu produto";
            this.tipoProd_txt.UseSystemPasswordChar = false;
            this.tipoProd_txt.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(642, 397);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(158, 25);
            this.bunifuLabel7.TabIndex = 32;
            this.bunifuLabel7.Text = "Tamanho do produto:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel7.UseGdiPlusTextRendering = true;
            // 
            // tamanhoProd_txt
            // 
            this.tamanhoProd_txt.AcceptsReturn = false;
            this.tamanhoProd_txt.AcceptsTab = false;
            this.tamanhoProd_txt.AnimationSpeed = 200;
            this.tamanhoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tamanhoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tamanhoProd_txt.AutoSizeHeight = true;
            this.tamanhoProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.tamanhoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tamanhoProd_txt.BackgroundImage")));
            this.tamanhoProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tamanhoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tamanhoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.tamanhoProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.tamanhoProd_txt.BorderRadius = 16;
            this.tamanhoProd_txt.BorderThickness = 1;
            this.tamanhoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tamanhoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tamanhoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tamanhoProd_txt.DefaultText = "";
            this.tamanhoProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.tamanhoProd_txt.ForeColor = System.Drawing.Color.White;
            this.tamanhoProd_txt.HideSelection = true;
            this.tamanhoProd_txt.IconLeft = null;
            this.tamanhoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.IconPadding = 10;
            this.tamanhoProd_txt.IconRight = null;
            this.tamanhoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.Lines = new string[0];
            this.tamanhoProd_txt.Location = new System.Drawing.Point(640, 428);
            this.tamanhoProd_txt.MaxLength = 32767;
            this.tamanhoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tamanhoProd_txt.Modified = false;
            this.tamanhoProd_txt.Multiline = true;
            this.tamanhoProd_txt.Name = "tamanhoProd_txt";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tamanhoProd_txt.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties52.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties52.ForeColor = System.Drawing.Color.White;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnIdleState = stateProperties52;
            this.tamanhoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tamanhoProd_txt.PasswordChar = '\0';
            this.tamanhoProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.tamanhoProd_txt.PlaceholderText = "Digite o tamanho do seu produto";
            this.tamanhoProd_txt.ReadOnly = false;
            this.tamanhoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tamanhoProd_txt.SelectedText = "";
            this.tamanhoProd_txt.SelectionLength = 0;
            this.tamanhoProd_txt.SelectionStart = 0;
            this.tamanhoProd_txt.ShortcutsEnabled = true;
            this.tamanhoProd_txt.Size = new System.Drawing.Size(419, 59);
            this.tamanhoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tamanhoProd_txt.TabIndex = 31;
            this.tamanhoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tamanhoProd_txt.TextMarginBottom = 0;
            this.tamanhoProd_txt.TextMarginLeft = 3;
            this.tamanhoProd_txt.TextMarginTop = 12;
            this.tamanhoProd_txt.TextPlaceholder = "Digite o tamanho do seu produto";
            this.tamanhoProd_txt.UseSystemPasswordChar = false;
            this.tamanhoProd_txt.WordWrap = true;
            // 
            // login_button
            // 
            this.login_button.AllowAnimations = true;
            this.login_button.AllowMouseEffects = true;
            this.login_button.AllowToggling = false;
            this.login_button.AnimationSpeed = 200;
            this.login_button.AutoGenerateColors = false;
            this.login_button.AutoRoundBorders = false;
            this.login_button.AutoSizeLeftIcon = true;
            this.login_button.AutoSizeRightIcon = true;
            this.login_button.BackColor = System.Drawing.Color.Transparent;
            this.login_button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("login_button.BackgroundImage")));
            this.login_button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.ButtonText = "Editar";
            this.login_button.ButtonTextMarginLeft = 0;
            this.login_button.ColorContrastOnClick = 45;
            this.login_button.ColorContrastOnHover = 45;
            this.login_button.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.login_button.CustomizableEdges = borderEdges3;
            this.login_button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.login_button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.login_button.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.login_button.ForeColor = System.Drawing.Color.White;
            this.login_button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.login_button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.login_button.IconMarginLeft = 11;
            this.login_button.IconPadding = 10;
            this.login_button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.login_button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.login_button.IconSize = 25;
            this.login_button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleBorderRadius = 10;
            this.login_button.IdleBorderThickness = 1;
            this.login_button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleIconLeftImage = null;
            this.login_button.IdleIconRightImage = null;
            this.login_button.IndicateFocus = false;
            this.login_button.Location = new System.Drawing.Point(642, 546);
            this.login_button.Name = "login_button";
            this.login_button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.OnDisabledState.BorderRadius = 10;
            this.login_button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnDisabledState.BorderThickness = 1;
            this.login_button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.OnDisabledState.IconLeftImage = null;
            this.login_button.OnDisabledState.IconRightImage = null;
            this.login_button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.BorderRadius = 10;
            this.login_button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.onHoverState.BorderThickness = 1;
            this.login_button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.login_button.onHoverState.IconLeftImage = null;
            this.login_button.onHoverState.IconRightImage = null;
            this.login_button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.BorderRadius = 10;
            this.login_button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnIdleState.BorderThickness = 1;
            this.login_button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnIdleState.IconLeftImage = null;
            this.login_button.OnIdleState.IconRightImage = null;
            this.login_button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.BorderRadius = 10;
            this.login_button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnPressedState.BorderThickness = 1;
            this.login_button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnPressedState.IconLeftImage = null;
            this.login_button.OnPressedState.IconRightImage = null;
            this.login_button.Size = new System.Drawing.Size(137, 39);
            this.login_button.TabIndex = 33;
            this.login_button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.login_button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.login_button.TextMarginLeft = 0;
            this.login_button.TextPadding = new System.Windows.Forms.Padding(0);
            this.login_button.UseDefaultRadiusAndThickness = true;
            this.login_button.Click += new System.EventHandler(this.login_button_Click);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Cancelar";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges4;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.bunifuButton21.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.IdleBorderRadius = 10;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(419, 546);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 10;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.BorderRadius = 10;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 10;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 10;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(137, 39);
            this.bunifuButton21.TabIndex = 34;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.pictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox1.Image = global::ProjetoJeffersonADM.Properties.Resources.icons8_close_50;
            this.pictureBox1.Location = new System.Drawing.Point(1074, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pictureBox1.TabIndex = 37;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(141, 63);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(102, 25);
            this.bunifuLabel8.TabIndex = 39;
            this.bunifuLabel8.Text = "Id do produto:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel8.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel8.UseGdiPlusTextRendering = true;
            // 
            // idProd_txt
            // 
            this.idProd_txt.AcceptsReturn = false;
            this.idProd_txt.AcceptsTab = false;
            this.idProd_txt.AnimationSpeed = 200;
            this.idProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idProd_txt.AutoSizeHeight = true;
            this.idProd_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idProd_txt.BackgroundImage")));
            this.idProd_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.idProd_txt.BorderRadius = 16;
            this.idProd_txt.BorderThickness = 1;
            this.idProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idProd_txt.DefaultText = "";
            this.idProd_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.idProd_txt.ForeColor = System.Drawing.Color.White;
            this.idProd_txt.HideSelection = true;
            this.idProd_txt.IconLeft = null;
            this.idProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.IconPadding = 10;
            this.idProd_txt.IconRight = null;
            this.idProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.Lines = new string[0];
            this.idProd_txt.Location = new System.Drawing.Point(141, 94);
            this.idProd_txt.MaxLength = 32767;
            this.idProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idProd_txt.Modified = false;
            this.idProd_txt.Multiline = true;
            this.idProd_txt.Name = "idProd_txt";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idProd_txt.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties56.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties56.ForeColor = System.Drawing.Color.White;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnIdleState = stateProperties56;
            this.idProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idProd_txt.PasswordChar = '\0';
            this.idProd_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.idProd_txt.PlaceholderText = "ID";
            this.idProd_txt.ReadOnly = false;
            this.idProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idProd_txt.SelectedText = "";
            this.idProd_txt.SelectionLength = 0;
            this.idProd_txt.SelectionStart = 0;
            this.idProd_txt.ShortcutsEnabled = true;
            this.idProd_txt.Size = new System.Drawing.Size(137, 59);
            this.idProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idProd_txt.TabIndex = 38;
            this.idProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idProd_txt.TextMarginBottom = 0;
            this.idProd_txt.TextMarginLeft = 3;
            this.idProd_txt.TextMarginTop = 12;
            this.idProd_txt.TextPlaceholder = "ID";
            this.idProd_txt.UseSystemPasswordChar = false;
            this.idProd_txt.WordWrap = true;
            // 
            // EditarProdutos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(1143, 642);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.idProd_txt);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.login_button);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.tamanhoProd_txt);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.tipoProd_txt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.precoProd_txt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.marcaProd_txt);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.descriProd_txt);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.nomeProd_txt);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "EditarProdutos";
            this.Text = "jtnyufghvkb6";
            this.Load += new System.EventHandler(this.EditarProdutos_Load_1);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox nomeProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox descriProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox marcaProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox precoProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox tipoProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox tamanhoProd_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 login_button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox idProd_txt;
    }
}