namespace ProjetoJeffersonADM
{
    partial class EditarProdutos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditarProdutos));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.label = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tamanhoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tipoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.precoProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.marcaProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.descriProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.idProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.nomeProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.corProd_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 40);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(110, 22);
            this.bunifuLabel1.TabIndex = 17;
            this.bunifuLabel1.Text = "ID do Produto:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 199);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(170, 22);
            this.bunifuLabel2.TabIndex = 19;
            this.bunifuLabel2.Text = "Descricao do Produto:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel3.Location = new System.Drawing.Point(12, 276);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(141, 22);
            this.bunifuLabel3.TabIndex = 21;
            this.bunifuLabel3.Text = "Marca do Produto:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel4.Location = new System.Drawing.Point(405, 276);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(139, 22);
            this.bunifuLabel4.TabIndex = 23;
            this.bunifuLabel4.Text = "Preço do Produto:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // label
            // 
            this.label.AllowParentOverrides = false;
            this.label.AutoEllipsis = false;
            this.label.CursorType = null;
            this.label.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label.ForeColor = System.Drawing.Color.Navy;
            this.label.Location = new System.Drawing.Point(405, 37);
            this.label.Name = "label";
            this.label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.label.Size = new System.Drawing.Size(128, 22);
            this.label.TabIndex = 25;
            this.label.Text = "Tipo do Produto:";
            this.label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel6.Location = new System.Drawing.Point(405, 118);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(167, 22);
            this.bunifuLabel6.TabIndex = 27;
            this.bunifuLabel6.Text = "Tamanho do Produto:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tamanhoProd_txt
            // 
            this.tamanhoProd_txt.AcceptsReturn = false;
            this.tamanhoProd_txt.AcceptsTab = false;
            this.tamanhoProd_txt.AnimationSpeed = 200;
            this.tamanhoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tamanhoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tamanhoProd_txt.AutoSizeHeight = false;
            this.tamanhoProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tamanhoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tamanhoProd_txt.BackgroundImage")));
            this.tamanhoProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tamanhoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tamanhoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tamanhoProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.tamanhoProd_txt.BorderRadius = 1;
            this.tamanhoProd_txt.BorderThickness = 0;
            this.tamanhoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tamanhoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tamanhoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tamanhoProd_txt.DefaultText = "";
            this.tamanhoProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.tamanhoProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.tamanhoProd_txt.HideSelection = true;
            this.tamanhoProd_txt.IconLeft = null;
            this.tamanhoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.IconPadding = 10;
            this.tamanhoProd_txt.IconRight = null;
            this.tamanhoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tamanhoProd_txt.Lines = new string[0];
            this.tamanhoProd_txt.Location = new System.Drawing.Point(405, 146);
            this.tamanhoProd_txt.MaxLength = 32767;
            this.tamanhoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tamanhoProd_txt.Modified = false;
            this.tamanhoProd_txt.Multiline = true;
            this.tamanhoProd_txt.Name = "tamanhoProd_txt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tamanhoProd_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties4.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties4.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tamanhoProd_txt.OnIdleState = stateProperties4;
            this.tamanhoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tamanhoProd_txt.PasswordChar = '\0';
            this.tamanhoProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tamanhoProd_txt.PlaceholderText = "M";
            this.tamanhoProd_txt.ReadOnly = false;
            this.tamanhoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tamanhoProd_txt.SelectedText = "";
            this.tamanhoProd_txt.SelectionLength = 0;
            this.tamanhoProd_txt.SelectionStart = 0;
            this.tamanhoProd_txt.ShortcutsEnabled = true;
            this.tamanhoProd_txt.Size = new System.Drawing.Size(349, 29);
            this.tamanhoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tamanhoProd_txt.TabIndex = 26;
            this.tamanhoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tamanhoProd_txt.TextMarginBottom = 0;
            this.tamanhoProd_txt.TextMarginLeft = 3;
            this.tamanhoProd_txt.TextMarginTop = 0;
            this.tamanhoProd_txt.TextPlaceholder = "M";
            this.tamanhoProd_txt.UseSystemPasswordChar = false;
            this.tamanhoProd_txt.WordWrap = true;
            // 
            // tipoProd_txt
            // 
            this.tipoProd_txt.AcceptsReturn = false;
            this.tipoProd_txt.AcceptsTab = false;
            this.tipoProd_txt.AnimationSpeed = 200;
            this.tipoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tipoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tipoProd_txt.AutoSizeHeight = false;
            this.tipoProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tipoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tipoProd_txt.BackgroundImage")));
            this.tipoProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tipoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tipoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tipoProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.tipoProd_txt.BorderRadius = 1;
            this.tipoProd_txt.BorderThickness = 0;
            this.tipoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tipoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tipoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tipoProd_txt.DefaultText = "";
            this.tipoProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.tipoProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.tipoProd_txt.HideSelection = true;
            this.tipoProd_txt.IconLeft = null;
            this.tipoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.IconPadding = 10;
            this.tipoProd_txt.IconRight = null;
            this.tipoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tipoProd_txt.Lines = new string[0];
            this.tipoProd_txt.Location = new System.Drawing.Point(405, 65);
            this.tipoProd_txt.MaxLength = 32767;
            this.tipoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tipoProd_txt.Modified = false;
            this.tipoProd_txt.Multiline = true;
            this.tipoProd_txt.Name = "tipoProd_txt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tipoProd_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties8.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties8.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tipoProd_txt.OnIdleState = stateProperties8;
            this.tipoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tipoProd_txt.PasswordChar = '\0';
            this.tipoProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tipoProd_txt.PlaceholderText = "Vestuario";
            this.tipoProd_txt.ReadOnly = false;
            this.tipoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tipoProd_txt.SelectedText = "";
            this.tipoProd_txt.SelectionLength = 0;
            this.tipoProd_txt.SelectionStart = 0;
            this.tipoProd_txt.ShortcutsEnabled = true;
            this.tipoProd_txt.Size = new System.Drawing.Size(349, 29);
            this.tipoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tipoProd_txt.TabIndex = 24;
            this.tipoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tipoProd_txt.TextMarginBottom = 0;
            this.tipoProd_txt.TextMarginLeft = 3;
            this.tipoProd_txt.TextMarginTop = 0;
            this.tipoProd_txt.TextPlaceholder = "Vestuario";
            this.tipoProd_txt.UseSystemPasswordChar = false;
            this.tipoProd_txt.WordWrap = true;
            // 
            // precoProd_txt
            // 
            this.precoProd_txt.AcceptsReturn = false;
            this.precoProd_txt.AcceptsTab = false;
            this.precoProd_txt.AnimationSpeed = 200;
            this.precoProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.precoProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.precoProd_txt.AutoSizeHeight = false;
            this.precoProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.precoProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("precoProd_txt.BackgroundImage")));
            this.precoProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.precoProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.precoProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.precoProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.precoProd_txt.BorderRadius = 1;
            this.precoProd_txt.BorderThickness = 0;
            this.precoProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.precoProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.precoProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.precoProd_txt.DefaultText = "";
            this.precoProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.precoProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.precoProd_txt.HideSelection = true;
            this.precoProd_txt.IconLeft = null;
            this.precoProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.IconPadding = 10;
            this.precoProd_txt.IconRight = null;
            this.precoProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.precoProd_txt.Lines = new string[0];
            this.precoProd_txt.Location = new System.Drawing.Point(405, 304);
            this.precoProd_txt.MaxLength = 32767;
            this.precoProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.precoProd_txt.Modified = false;
            this.precoProd_txt.Multiline = true;
            this.precoProd_txt.Name = "precoProd_txt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.precoProd_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.precoProd_txt.OnIdleState = stateProperties12;
            this.precoProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.precoProd_txt.PasswordChar = '\0';
            this.precoProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.precoProd_txt.PlaceholderText = "R$ 190.00";
            this.precoProd_txt.ReadOnly = false;
            this.precoProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.precoProd_txt.SelectedText = "";
            this.precoProd_txt.SelectionLength = 0;
            this.precoProd_txt.SelectionStart = 0;
            this.precoProd_txt.ShortcutsEnabled = true;
            this.precoProd_txt.Size = new System.Drawing.Size(349, 29);
            this.precoProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.precoProd_txt.TabIndex = 22;
            this.precoProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.precoProd_txt.TextMarginBottom = 0;
            this.precoProd_txt.TextMarginLeft = 3;
            this.precoProd_txt.TextMarginTop = 0;
            this.precoProd_txt.TextPlaceholder = "R$ 190.00";
            this.precoProd_txt.UseSystemPasswordChar = false;
            this.precoProd_txt.WordWrap = true;
            // 
            // marcaProd_txt
            // 
            this.marcaProd_txt.AcceptsReturn = false;
            this.marcaProd_txt.AcceptsTab = false;
            this.marcaProd_txt.AnimationSpeed = 200;
            this.marcaProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.marcaProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.marcaProd_txt.AutoSizeHeight = false;
            this.marcaProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.marcaProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("marcaProd_txt.BackgroundImage")));
            this.marcaProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.marcaProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.marcaProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.marcaProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.marcaProd_txt.BorderRadius = 1;
            this.marcaProd_txt.BorderThickness = 0;
            this.marcaProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.marcaProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.marcaProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.marcaProd_txt.DefaultText = "";
            this.marcaProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.marcaProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.marcaProd_txt.HideSelection = true;
            this.marcaProd_txt.IconLeft = null;
            this.marcaProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.IconPadding = 10;
            this.marcaProd_txt.IconRight = null;
            this.marcaProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.marcaProd_txt.Lines = new string[0];
            this.marcaProd_txt.Location = new System.Drawing.Point(12, 304);
            this.marcaProd_txt.MaxLength = 32767;
            this.marcaProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.marcaProd_txt.Modified = false;
            this.marcaProd_txt.Multiline = true;
            this.marcaProd_txt.Name = "marcaProd_txt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.marcaProd_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.marcaProd_txt.OnIdleState = stateProperties16;
            this.marcaProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.marcaProd_txt.PasswordChar = '\0';
            this.marcaProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.marcaProd_txt.PlaceholderText = "Nike";
            this.marcaProd_txt.ReadOnly = false;
            this.marcaProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.marcaProd_txt.SelectedText = "";
            this.marcaProd_txt.SelectionLength = 0;
            this.marcaProd_txt.SelectionStart = 0;
            this.marcaProd_txt.ShortcutsEnabled = true;
            this.marcaProd_txt.Size = new System.Drawing.Size(349, 29);
            this.marcaProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.marcaProd_txt.TabIndex = 20;
            this.marcaProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.marcaProd_txt.TextMarginBottom = 0;
            this.marcaProd_txt.TextMarginLeft = 3;
            this.marcaProd_txt.TextMarginTop = 0;
            this.marcaProd_txt.TextPlaceholder = "Nike";
            this.marcaProd_txt.UseSystemPasswordChar = false;
            this.marcaProd_txt.WordWrap = true;
            // 
            // descriProd_txt
            // 
            this.descriProd_txt.AcceptsReturn = false;
            this.descriProd_txt.AcceptsTab = false;
            this.descriProd_txt.AnimationSpeed = 200;
            this.descriProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.descriProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.descriProd_txt.AutoSizeHeight = false;
            this.descriProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.descriProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("descriProd_txt.BackgroundImage")));
            this.descriProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.descriProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.descriProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.descriProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.descriProd_txt.BorderRadius = 1;
            this.descriProd_txt.BorderThickness = 0;
            this.descriProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.descriProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.descriProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.descriProd_txt.DefaultText = "";
            this.descriProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.descriProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.descriProd_txt.HideSelection = true;
            this.descriProd_txt.IconLeft = null;
            this.descriProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.IconPadding = 10;
            this.descriProd_txt.IconRight = null;
            this.descriProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriProd_txt.Lines = new string[0];
            this.descriProd_txt.Location = new System.Drawing.Point(12, 227);
            this.descriProd_txt.MaxLength = 32767;
            this.descriProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.descriProd_txt.Modified = false;
            this.descriProd_txt.Multiline = true;
            this.descriProd_txt.Name = "descriProd_txt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.descriProd_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties20.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties20.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriProd_txt.OnIdleState = stateProperties20;
            this.descriProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.descriProd_txt.PasswordChar = '\0';
            this.descriProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.descriProd_txt.PlaceholderText = "Camisa de Algodao";
            this.descriProd_txt.ReadOnly = false;
            this.descriProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.descriProd_txt.SelectedText = "";
            this.descriProd_txt.SelectionLength = 0;
            this.descriProd_txt.SelectionStart = 0;
            this.descriProd_txt.ShortcutsEnabled = true;
            this.descriProd_txt.Size = new System.Drawing.Size(349, 29);
            this.descriProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.descriProd_txt.TabIndex = 18;
            this.descriProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.descriProd_txt.TextMarginBottom = 0;
            this.descriProd_txt.TextMarginLeft = 3;
            this.descriProd_txt.TextMarginTop = 0;
            this.descriProd_txt.TextPlaceholder = "Camisa de Algodao";
            this.descriProd_txt.UseSystemPasswordChar = false;
            this.descriProd_txt.WordWrap = true;
            // 
            // idProd_txt
            // 
            this.idProd_txt.AcceptsReturn = false;
            this.idProd_txt.AcceptsTab = false;
            this.idProd_txt.AnimationSpeed = 200;
            this.idProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idProd_txt.AutoSizeHeight = false;
            this.idProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.idProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idProd_txt.BackgroundImage")));
            this.idProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.idProd_txt.BorderRadius = 1;
            this.idProd_txt.BorderThickness = 0;
            this.idProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idProd_txt.DefaultText = "";
            this.idProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.idProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.idProd_txt.HideSelection = true;
            this.idProd_txt.IconLeft = null;
            this.idProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.IconPadding = 10;
            this.idProd_txt.IconRight = null;
            this.idProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idProd_txt.Lines = new string[0];
            this.idProd_txt.Location = new System.Drawing.Point(12, 68);
            this.idProd_txt.MaxLength = 32767;
            this.idProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.idProd_txt.Modified = false;
            this.idProd_txt.Multiline = true;
            this.idProd_txt.Name = "idProd_txt";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idProd_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties24.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties24.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idProd_txt.OnIdleState = stateProperties24;
            this.idProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.idProd_txt.PasswordChar = '\0';
            this.idProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idProd_txt.PlaceholderText = "Camiseta";
            this.idProd_txt.ReadOnly = true;
            this.idProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idProd_txt.SelectedText = "";
            this.idProd_txt.SelectionLength = 0;
            this.idProd_txt.SelectionStart = 0;
            this.idProd_txt.ShortcutsEnabled = true;
            this.idProd_txt.Size = new System.Drawing.Size(110, 26);
            this.idProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idProd_txt.TabIndex = 16;
            this.idProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.idProd_txt.TextMarginBottom = 0;
            this.idProd_txt.TextMarginLeft = 3;
            this.idProd_txt.TextMarginTop = 0;
            this.idProd_txt.TextPlaceholder = "Camiseta";
            this.idProd_txt.UseSystemPasswordChar = false;
            this.idProd_txt.WordWrap = true;
            // 
            // add_btn
            // 
            this.add_btn.AllowAnimations = true;
            this.add_btn.AllowMouseEffects = true;
            this.add_btn.AllowToggling = false;
            this.add_btn.AnimationSpeed = 200;
            this.add_btn.AutoGenerateColors = false;
            this.add_btn.AutoRoundBorders = false;
            this.add_btn.AutoSizeLeftIcon = true;
            this.add_btn.AutoSizeRightIcon = true;
            this.add_btn.BackColor = System.Drawing.Color.Transparent;
            this.add_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("add_btn.BackgroundImage")));
            this.add_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.ButtonText = "Editar";
            this.add_btn.ButtonTextMarginLeft = 0;
            this.add_btn.ColorContrastOnClick = 45;
            this.add_btn.ColorContrastOnHover = 45;
            this.add_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.add_btn.CustomizableEdges = borderEdges1;
            this.add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.add_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.add_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.add_btn.Font = new System.Drawing.Font("Raleway", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.add_btn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.add_btn.IconLeft = null;
            this.add_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.add_btn.IconMarginLeft = 11;
            this.add_btn.IconPadding = 10;
            this.add_btn.IconRight = null;
            this.add_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.add_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.add_btn.IconSize = 25;
            this.add_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.add_btn.IdleBorderRadius = 0;
            this.add_btn.IdleBorderThickness = 0;
            this.add_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.add_btn.IdleIconLeftImage = null;
            this.add_btn.IdleIconRightImage = null;
            this.add_btn.IndicateFocus = false;
            this.add_btn.Location = new System.Drawing.Point(287, 366);
            this.add_btn.Name = "add_btn";
            this.add_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.OnDisabledState.BorderRadius = 1;
            this.add_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnDisabledState.BorderThickness = 1;
            this.add_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.add_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.add_btn.OnDisabledState.IconLeftImage = null;
            this.add_btn.OnDisabledState.IconRightImage = null;
            this.add_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.BorderRadius = 1;
            this.add_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.onHoverState.BorderThickness = 1;
            this.add_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.add_btn.onHoverState.IconLeftImage = null;
            this.add_btn.onHoverState.IconRightImage = null;
            this.add_btn.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.add_btn.OnIdleState.BorderRadius = 1;
            this.add_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnIdleState.BorderThickness = 1;
            this.add_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.add_btn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.add_btn.OnIdleState.IconLeftImage = null;
            this.add_btn.OnIdleState.IconRightImage = null;
            this.add_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.BorderRadius = 1;
            this.add_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.add_btn.OnPressedState.BorderThickness = 1;
            this.add_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.add_btn.OnPressedState.IconLeftImage = null;
            this.add_btn.OnPressedState.IconRightImage = null;
            this.add_btn.Size = new System.Drawing.Size(227, 50);
            this.add_btn.TabIndex = 0;
            this.add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.add_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.add_btn.TextMarginLeft = 0;
            this.add_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.add_btn.UseDefaultRadiusAndThickness = true;
            this.add_btn.Click += new System.EventHandler(this.add_btn_Click);
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel5.Location = new System.Drawing.Point(12, 118);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(141, 22);
            this.bunifuLabel5.TabIndex = 29;
            this.bunifuLabel5.Text = "Nome do Produto:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nomeProd_txt
            // 
            this.nomeProd_txt.AcceptsReturn = false;
            this.nomeProd_txt.AcceptsTab = false;
            this.nomeProd_txt.AnimationSpeed = 200;
            this.nomeProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomeProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomeProd_txt.AutoSizeHeight = false;
            this.nomeProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.nomeProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomeProd_txt.BackgroundImage")));
            this.nomeProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nomeProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomeProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nomeProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.nomeProd_txt.BorderRadius = 1;
            this.nomeProd_txt.BorderThickness = 0;
            this.nomeProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomeProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomeProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomeProd_txt.DefaultText = "";
            this.nomeProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.nomeProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.nomeProd_txt.HideSelection = true;
            this.nomeProd_txt.IconLeft = null;
            this.nomeProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.IconPadding = 10;
            this.nomeProd_txt.IconRight = null;
            this.nomeProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeProd_txt.Lines = new string[0];
            this.nomeProd_txt.Location = new System.Drawing.Point(12, 146);
            this.nomeProd_txt.MaxLength = 32767;
            this.nomeProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomeProd_txt.Modified = false;
            this.nomeProd_txt.Multiline = true;
            this.nomeProd_txt.Name = "nomeProd_txt";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomeProd_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties28.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties28.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeProd_txt.OnIdleState = stateProperties28;
            this.nomeProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.nomeProd_txt.PasswordChar = '\0';
            this.nomeProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nomeProd_txt.PlaceholderText = "Camisa Alagoana";
            this.nomeProd_txt.ReadOnly = false;
            this.nomeProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomeProd_txt.SelectedText = "";
            this.nomeProd_txt.SelectionLength = 0;
            this.nomeProd_txt.SelectionStart = 0;
            this.nomeProd_txt.ShortcutsEnabled = true;
            this.nomeProd_txt.Size = new System.Drawing.Size(349, 29);
            this.nomeProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomeProd_txt.TabIndex = 28;
            this.nomeProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.nomeProd_txt.TextMarginBottom = 0;
            this.nomeProd_txt.TextMarginLeft = 3;
            this.nomeProd_txt.TextMarginTop = 0;
            this.nomeProd_txt.TextPlaceholder = "Camisa Alagoana";
            this.nomeProd_txt.UseSystemPasswordChar = false;
            this.nomeProd_txt.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Raleway", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.Navy;
            this.bunifuLabel7.Location = new System.Drawing.Point(405, 199);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(121, 22);
            this.bunifuLabel7.TabIndex = 31;
            this.bunifuLabel7.Text = "Cor do Produto:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // corProd_txt
            // 
            this.corProd_txt.AcceptsReturn = false;
            this.corProd_txt.AcceptsTab = false;
            this.corProd_txt.AnimationSpeed = 200;
            this.corProd_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.corProd_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.corProd_txt.AutoSizeHeight = false;
            this.corProd_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.corProd_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("corProd_txt.BackgroundImage")));
            this.corProd_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.corProd_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.corProd_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.corProd_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.corProd_txt.BorderRadius = 1;
            this.corProd_txt.BorderThickness = 0;
            this.corProd_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.corProd_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.corProd_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.corProd_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.corProd_txt.DefaultText = "";
            this.corProd_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.corProd_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.corProd_txt.HideSelection = true;
            this.corProd_txt.IconLeft = null;
            this.corProd_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.corProd_txt.IconPadding = 10;
            this.corProd_txt.IconRight = null;
            this.corProd_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.corProd_txt.Lines = new string[0];
            this.corProd_txt.Location = new System.Drawing.Point(405, 227);
            this.corProd_txt.MaxLength = 32767;
            this.corProd_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.corProd_txt.Modified = false;
            this.corProd_txt.Multiline = true;
            this.corProd_txt.Name = "corProd_txt";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.corProd_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.corProd_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.corProd_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties32.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties32.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.corProd_txt.OnIdleState = stateProperties32;
            this.corProd_txt.Padding = new System.Windows.Forms.Padding(3);
            this.corProd_txt.PasswordChar = '\0';
            this.corProd_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.corProd_txt.PlaceholderText = "Camisa de Algodao";
            this.corProd_txt.ReadOnly = false;
            this.corProd_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.corProd_txt.SelectedText = "";
            this.corProd_txt.SelectionLength = 0;
            this.corProd_txt.SelectionStart = 0;
            this.corProd_txt.ShortcutsEnabled = true;
            this.corProd_txt.Size = new System.Drawing.Size(349, 29);
            this.corProd_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.corProd_txt.TabIndex = 30;
            this.corProd_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.corProd_txt.TextMarginBottom = 0;
            this.corProd_txt.TextMarginLeft = 3;
            this.corProd_txt.TextMarginTop = 0;
            this.corProd_txt.TextPlaceholder = "Camisa de Algodao";
            this.corProd_txt.UseSystemPasswordChar = false;
            this.corProd_txt.WordWrap = true;
            // 
            // EditarProdutos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(800, 425);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.corProd_txt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.nomeProd_txt);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.tamanhoProd_txt);
            this.Controls.Add(this.label);
            this.Controls.Add(this.tipoProd_txt);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.precoProd_txt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.marcaProd_txt);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.descriProd_txt);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.idProd_txt);
            this.Controls.Add(this.add_btn);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "EditarProdutos";
            this.Text = "AdicionarProdutos";
            this.Load += new System.EventHandler(this.EditarProdutos_Load);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.EditarProdutos_MouseDown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.EditarProdutos_MouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.EditarProdutos_MouseUp);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton add_btn;
        private Bunifu.UI.WinForms.BunifuTextBox idProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox descriProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox marcaProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox precoProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel label;
        private Bunifu.UI.WinForms.BunifuTextBox tipoProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox tamanhoProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox nomeProd_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox corProd_txt;
    }
}