namespace ProjetoJeffersonADM.PaginaInicial.Fornecedor
{
    partial class AdicionarFornecedor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdicionarFornecedor));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.emailFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.login_button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.estadoFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cidadeFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bairroFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cnpjFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nomeFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ruaFornecedor_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Archivo Black", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(381, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(453, 60);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Adicionar fornecedor";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel1.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(53, 84);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(156, 25);
            this.bunifuLabel4.TabIndex = 22;
            this.bunifuLabel4.Text = "Nome do fornecedor:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel4.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(57, 206);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(113, 25);
            this.bunifuLabel3.TabIndex = 26;
            this.bunifuLabel3.Text = "Cnpj do cliente:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel3.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(57, 426);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(157, 25);
            this.bunifuLabel5.TabIndex = 28;
            this.bunifuLabel5.Text = "Bairro do fornecedor:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel5.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(554, 84);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(164, 25);
            this.bunifuLabel6.TabIndex = 30;
            this.bunifuLabel6.Text = "Cidade do fornecedor:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel6.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel6.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(554, 205);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(164, 25);
            this.bunifuLabel7.TabIndex = 32;
            this.bunifuLabel7.Text = "Estado do fornecedor:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel7.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel9.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel9.Location = new System.Drawing.Point(556, 312);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(158, 25);
            this.bunifuLabel9.TabIndex = 39;
            this.bunifuLabel9.Text = "E-mail do fornecedor:";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel9.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel9.UseGdiPlusTextRendering = true;
            // 
            // emailFornecedor_txt
            // 
            this.emailFornecedor_txt.AcceptsReturn = false;
            this.emailFornecedor_txt.AcceptsTab = false;
            this.emailFornecedor_txt.AnimationSpeed = 200;
            this.emailFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailFornecedor_txt.AutoSizeHeight = true;
            this.emailFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.emailFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailFornecedor_txt.BackgroundImage")));
            this.emailFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.emailFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.emailFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.emailFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.emailFornecedor_txt.BorderRadius = 16;
            this.emailFornecedor_txt.BorderThickness = 1;
            this.emailFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.emailFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailFornecedor_txt.DefaultText = "";
            this.emailFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.emailFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.emailFornecedor_txt.HideSelection = true;
            this.emailFornecedor_txt.IconLeft = null;
            this.emailFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedor_txt.IconPadding = 10;
            this.emailFornecedor_txt.IconRight = null;
            this.emailFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedor_txt.Lines = new string[0];
            this.emailFornecedor_txt.Location = new System.Drawing.Point(554, 343);
            this.emailFornecedor_txt.MaxLength = 32767;
            this.emailFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailFornecedor_txt.Modified = false;
            this.emailFornecedor_txt.Multiline = true;
            this.emailFornecedor_txt.Name = "emailFornecedor_txt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedor_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailFornecedor_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedor_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedor_txt.OnIdleState = stateProperties4;
            this.emailFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.emailFornecedor_txt.PasswordChar = '\0';
            this.emailFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.emailFornecedor_txt.PlaceholderText = "Digite o e-mail do fornecedor";
            this.emailFornecedor_txt.ReadOnly = false;
            this.emailFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailFornecedor_txt.SelectedText = "";
            this.emailFornecedor_txt.SelectionLength = 0;
            this.emailFornecedor_txt.SelectionStart = 0;
            this.emailFornecedor_txt.ShortcutsEnabled = true;
            this.emailFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.emailFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailFornecedor_txt.TabIndex = 38;
            this.emailFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailFornecedor_txt.TextMarginBottom = 0;
            this.emailFornecedor_txt.TextMarginLeft = 3;
            this.emailFornecedor_txt.TextMarginTop = 12;
            this.emailFornecedor_txt.TextPlaceholder = "Digite o e-mail do fornecedor";
            this.emailFornecedor_txt.UseSystemPasswordChar = false;
            this.emailFornecedor_txt.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.pictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox1.Image = global::ProjetoJeffersonADM.Properties.Resources.icons8_close_50;
            this.pictureBox1.Location = new System.Drawing.Point(1074, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pictureBox1.TabIndex = 37;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Cancelar";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.bunifuButton21.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.IdleBorderRadius = 10;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(335, 580);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 10;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.BorderRadius = 10;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 10;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 10;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(137, 39);
            this.bunifuButton21.TabIndex = 34;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // login_button
            // 
            this.login_button.AllowAnimations = true;
            this.login_button.AllowMouseEffects = true;
            this.login_button.AllowToggling = false;
            this.login_button.AnimationSpeed = 200;
            this.login_button.AutoGenerateColors = false;
            this.login_button.AutoRoundBorders = false;
            this.login_button.AutoSizeLeftIcon = true;
            this.login_button.AutoSizeRightIcon = true;
            this.login_button.BackColor = System.Drawing.Color.Transparent;
            this.login_button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("login_button.BackgroundImage")));
            this.login_button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.ButtonText = "Adicionar";
            this.login_button.ButtonTextMarginLeft = 0;
            this.login_button.ColorContrastOnClick = 45;
            this.login_button.ColorContrastOnHover = 45;
            this.login_button.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.login_button.CustomizableEdges = borderEdges2;
            this.login_button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.login_button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.login_button.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.login_button.ForeColor = System.Drawing.Color.White;
            this.login_button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.login_button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.login_button.IconMarginLeft = 11;
            this.login_button.IconPadding = 10;
            this.login_button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.login_button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.login_button.IconSize = 25;
            this.login_button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleBorderRadius = 10;
            this.login_button.IdleBorderThickness = 1;
            this.login_button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.IdleIconLeftImage = null;
            this.login_button.IdleIconRightImage = null;
            this.login_button.IndicateFocus = false;
            this.login_button.Location = new System.Drawing.Point(617, 580);
            this.login_button.Name = "login_button";
            this.login_button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.OnDisabledState.BorderRadius = 10;
            this.login_button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnDisabledState.BorderThickness = 1;
            this.login_button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.OnDisabledState.IconLeftImage = null;
            this.login_button.OnDisabledState.IconRightImage = null;
            this.login_button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.BorderRadius = 10;
            this.login_button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.onHoverState.BorderThickness = 1;
            this.login_button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.login_button.onHoverState.IconLeftImage = null;
            this.login_button.onHoverState.IconRightImage = null;
            this.login_button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.BorderRadius = 10;
            this.login_button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnIdleState.BorderThickness = 1;
            this.login_button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnIdleState.IconLeftImage = null;
            this.login_button.OnIdleState.IconRightImage = null;
            this.login_button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.BorderRadius = 10;
            this.login_button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnPressedState.BorderThickness = 1;
            this.login_button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnPressedState.IconLeftImage = null;
            this.login_button.OnPressedState.IconRightImage = null;
            this.login_button.Size = new System.Drawing.Size(137, 39);
            this.login_button.TabIndex = 33;
            this.login_button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.login_button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.login_button.TextMarginLeft = 0;
            this.login_button.TextPadding = new System.Windows.Forms.Padding(0);
            this.login_button.UseDefaultRadiusAndThickness = true;
            this.login_button.Click += new System.EventHandler(this.login_button_Click);
            // 
            // estadoFornecedor_txt
            // 
            this.estadoFornecedor_txt.AcceptsReturn = false;
            this.estadoFornecedor_txt.AcceptsTab = false;
            this.estadoFornecedor_txt.AnimationSpeed = 200;
            this.estadoFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.estadoFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.estadoFornecedor_txt.AutoSizeHeight = true;
            this.estadoFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.estadoFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("estadoFornecedor_txt.BackgroundImage")));
            this.estadoFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.estadoFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.estadoFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.estadoFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.estadoFornecedor_txt.BorderRadius = 16;
            this.estadoFornecedor_txt.BorderThickness = 1;
            this.estadoFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.estadoFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.estadoFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.estadoFornecedor_txt.DefaultText = "";
            this.estadoFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.estadoFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.estadoFornecedor_txt.HideSelection = true;
            this.estadoFornecedor_txt.IconLeft = null;
            this.estadoFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoFornecedor_txt.IconPadding = 10;
            this.estadoFornecedor_txt.IconRight = null;
            this.estadoFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.estadoFornecedor_txt.Lines = new string[0];
            this.estadoFornecedor_txt.Location = new System.Drawing.Point(552, 236);
            this.estadoFornecedor_txt.MaxLength = 32767;
            this.estadoFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.estadoFornecedor_txt.Modified = false;
            this.estadoFornecedor_txt.Multiline = true;
            this.estadoFornecedor_txt.Name = "estadoFornecedor_txt";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoFornecedor_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.estadoFornecedor_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoFornecedor_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.estadoFornecedor_txt.OnIdleState = stateProperties8;
            this.estadoFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.estadoFornecedor_txt.PasswordChar = '\0';
            this.estadoFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.estadoFornecedor_txt.PlaceholderText = "Digite o estado do fornecedor";
            this.estadoFornecedor_txt.ReadOnly = false;
            this.estadoFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.estadoFornecedor_txt.SelectedText = "";
            this.estadoFornecedor_txt.SelectionLength = 0;
            this.estadoFornecedor_txt.SelectionStart = 0;
            this.estadoFornecedor_txt.ShortcutsEnabled = true;
            this.estadoFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.estadoFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.estadoFornecedor_txt.TabIndex = 31;
            this.estadoFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.estadoFornecedor_txt.TextMarginBottom = 0;
            this.estadoFornecedor_txt.TextMarginLeft = 3;
            this.estadoFornecedor_txt.TextMarginTop = 12;
            this.estadoFornecedor_txt.TextPlaceholder = "Digite o estado do fornecedor";
            this.estadoFornecedor_txt.UseSystemPasswordChar = false;
            this.estadoFornecedor_txt.WordWrap = true;
            // 
            // cidadeFornecedor_txt
            // 
            this.cidadeFornecedor_txt.AcceptsReturn = false;
            this.cidadeFornecedor_txt.AcceptsTab = false;
            this.cidadeFornecedor_txt.AnimationSpeed = 200;
            this.cidadeFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cidadeFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cidadeFornecedor_txt.AutoSizeHeight = true;
            this.cidadeFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cidadeFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cidadeFornecedor_txt.BackgroundImage")));
            this.cidadeFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cidadeFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cidadeFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cidadeFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.cidadeFornecedor_txt.BorderRadius = 16;
            this.cidadeFornecedor_txt.BorderThickness = 1;
            this.cidadeFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cidadeFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cidadeFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cidadeFornecedor_txt.DefaultText = "";
            this.cidadeFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cidadeFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.cidadeFornecedor_txt.HideSelection = true;
            this.cidadeFornecedor_txt.IconLeft = null;
            this.cidadeFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeFornecedor_txt.IconPadding = 10;
            this.cidadeFornecedor_txt.IconRight = null;
            this.cidadeFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cidadeFornecedor_txt.Lines = new string[0];
            this.cidadeFornecedor_txt.Location = new System.Drawing.Point(552, 115);
            this.cidadeFornecedor_txt.MaxLength = 32767;
            this.cidadeFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cidadeFornecedor_txt.Modified = false;
            this.cidadeFornecedor_txt.Multiline = true;
            this.cidadeFornecedor_txt.Name = "cidadeFornecedor_txt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeFornecedor_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cidadeFornecedor_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeFornecedor_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cidadeFornecedor_txt.OnIdleState = stateProperties12;
            this.cidadeFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.cidadeFornecedor_txt.PasswordChar = '\0';
            this.cidadeFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.cidadeFornecedor_txt.PlaceholderText = "Digite a cidade do fornecedor";
            this.cidadeFornecedor_txt.ReadOnly = false;
            this.cidadeFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cidadeFornecedor_txt.SelectedText = "";
            this.cidadeFornecedor_txt.SelectionLength = 0;
            this.cidadeFornecedor_txt.SelectionStart = 0;
            this.cidadeFornecedor_txt.ShortcutsEnabled = true;
            this.cidadeFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.cidadeFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cidadeFornecedor_txt.TabIndex = 29;
            this.cidadeFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cidadeFornecedor_txt.TextMarginBottom = 0;
            this.cidadeFornecedor_txt.TextMarginLeft = 3;
            this.cidadeFornecedor_txt.TextMarginTop = 12;
            this.cidadeFornecedor_txt.TextPlaceholder = "Digite a cidade do fornecedor";
            this.cidadeFornecedor_txt.UseSystemPasswordChar = false;
            this.cidadeFornecedor_txt.WordWrap = true;
            // 
            // bairroFornecedor_txt
            // 
            this.bairroFornecedor_txt.AcceptsReturn = false;
            this.bairroFornecedor_txt.AcceptsTab = false;
            this.bairroFornecedor_txt.AnimationSpeed = 200;
            this.bairroFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bairroFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bairroFornecedor_txt.AutoSizeHeight = true;
            this.bairroFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bairroFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bairroFornecedor_txt.BackgroundImage")));
            this.bairroFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bairroFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bairroFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bairroFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bairroFornecedor_txt.BorderRadius = 16;
            this.bairroFornecedor_txt.BorderThickness = 1;
            this.bairroFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.bairroFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bairroFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bairroFornecedor_txt.DefaultText = "";
            this.bairroFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bairroFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.bairroFornecedor_txt.HideSelection = true;
            this.bairroFornecedor_txt.IconLeft = null;
            this.bairroFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroFornecedor_txt.IconPadding = 10;
            this.bairroFornecedor_txt.IconRight = null;
            this.bairroFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bairroFornecedor_txt.Lines = new string[0];
            this.bairroFornecedor_txt.Location = new System.Drawing.Point(55, 457);
            this.bairroFornecedor_txt.MaxLength = 32767;
            this.bairroFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.bairroFornecedor_txt.Modified = false;
            this.bairroFornecedor_txt.Multiline = true;
            this.bairroFornecedor_txt.Name = "bairroFornecedor_txt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroFornecedor_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bairroFornecedor_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroFornecedor_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bairroFornecedor_txt.OnIdleState = stateProperties16;
            this.bairroFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.bairroFornecedor_txt.PasswordChar = '\0';
            this.bairroFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.bairroFornecedor_txt.PlaceholderText = "Bairro do fornecedor";
            this.bairroFornecedor_txt.ReadOnly = false;
            this.bairroFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bairroFornecedor_txt.SelectedText = "";
            this.bairroFornecedor_txt.SelectionLength = 0;
            this.bairroFornecedor_txt.SelectionStart = 0;
            this.bairroFornecedor_txt.ShortcutsEnabled = true;
            this.bairroFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.bairroFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bairroFornecedor_txt.TabIndex = 27;
            this.bairroFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bairroFornecedor_txt.TextMarginBottom = 0;
            this.bairroFornecedor_txt.TextMarginLeft = 3;
            this.bairroFornecedor_txt.TextMarginTop = 12;
            this.bairroFornecedor_txt.TextPlaceholder = "Bairro do fornecedor";
            this.bairroFornecedor_txt.UseSystemPasswordChar = false;
            this.bairroFornecedor_txt.WordWrap = true;
            // 
            // cnpjFornecedor_txt
            // 
            this.cnpjFornecedor_txt.AcceptsReturn = false;
            this.cnpjFornecedor_txt.AcceptsTab = false;
            this.cnpjFornecedor_txt.AnimationSpeed = 200;
            this.cnpjFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cnpjFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cnpjFornecedor_txt.AutoSizeHeight = true;
            this.cnpjFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cnpjFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cnpjFornecedor_txt.BackgroundImage")));
            this.cnpjFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpjFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpjFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpjFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.cnpjFornecedor_txt.BorderRadius = 16;
            this.cnpjFornecedor_txt.BorderThickness = 1;
            this.cnpjFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cnpjFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cnpjFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cnpjFornecedor_txt.DefaultText = "";
            this.cnpjFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cnpjFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.cnpjFornecedor_txt.HideSelection = true;
            this.cnpjFornecedor_txt.IconLeft = null;
            this.cnpjFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedor_txt.IconPadding = 10;
            this.cnpjFornecedor_txt.IconRight = null;
            this.cnpjFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedor_txt.Lines = new string[0];
            this.cnpjFornecedor_txt.Location = new System.Drawing.Point(55, 237);
            this.cnpjFornecedor_txt.MaxLength = 32767;
            this.cnpjFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cnpjFornecedor_txt.Modified = false;
            this.cnpjFornecedor_txt.Multiline = true;
            this.cnpjFornecedor_txt.Name = "cnpjFornecedor_txt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedor_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cnpjFornecedor_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedor_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedor_txt.OnIdleState = stateProperties20;
            this.cnpjFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.cnpjFornecedor_txt.PasswordChar = '\0';
            this.cnpjFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.cnpjFornecedor_txt.PlaceholderText = "Digite o cnpj do fornecedor";
            this.cnpjFornecedor_txt.ReadOnly = false;
            this.cnpjFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cnpjFornecedor_txt.SelectedText = "";
            this.cnpjFornecedor_txt.SelectionLength = 0;
            this.cnpjFornecedor_txt.SelectionStart = 0;
            this.cnpjFornecedor_txt.ShortcutsEnabled = true;
            this.cnpjFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.cnpjFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cnpjFornecedor_txt.TabIndex = 25;
            this.cnpjFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cnpjFornecedor_txt.TextMarginBottom = 0;
            this.cnpjFornecedor_txt.TextMarginLeft = 3;
            this.cnpjFornecedor_txt.TextMarginTop = 12;
            this.cnpjFornecedor_txt.TextPlaceholder = "Digite o cnpj do fornecedor";
            this.cnpjFornecedor_txt.UseSystemPasswordChar = false;
            this.cnpjFornecedor_txt.WordWrap = true;
            // 
            // nomeFornecedor_txt
            // 
            this.nomeFornecedor_txt.AcceptsReturn = false;
            this.nomeFornecedor_txt.AcceptsTab = false;
            this.nomeFornecedor_txt.AnimationSpeed = 200;
            this.nomeFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomeFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomeFornecedor_txt.AutoSizeHeight = true;
            this.nomeFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomeFornecedor_txt.BackgroundImage")));
            this.nomeFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.nomeFornecedor_txt.BorderRadius = 16;
            this.nomeFornecedor_txt.BorderThickness = 1;
            this.nomeFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomeFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomeFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomeFornecedor_txt.DefaultText = "";
            this.nomeFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.nomeFornecedor_txt.HideSelection = true;
            this.nomeFornecedor_txt.IconLeft = null;
            this.nomeFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeFornecedor_txt.IconPadding = 10;
            this.nomeFornecedor_txt.IconRight = null;
            this.nomeFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeFornecedor_txt.Lines = new string[0];
            this.nomeFornecedor_txt.Location = new System.Drawing.Point(51, 115);
            this.nomeFornecedor_txt.MaxLength = 32767;
            this.nomeFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomeFornecedor_txt.Modified = false;
            this.nomeFornecedor_txt.Multiline = true;
            this.nomeFornecedor_txt.Name = "nomeFornecedor_txt";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeFornecedor_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomeFornecedor_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeFornecedor_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeFornecedor_txt.OnIdleState = stateProperties24;
            this.nomeFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.nomeFornecedor_txt.PasswordChar = '\0';
            this.nomeFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.nomeFornecedor_txt.PlaceholderText = "Digite o nome do fornecedor";
            this.nomeFornecedor_txt.ReadOnly = false;
            this.nomeFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomeFornecedor_txt.SelectedText = "";
            this.nomeFornecedor_txt.SelectionLength = 0;
            this.nomeFornecedor_txt.SelectionStart = 0;
            this.nomeFornecedor_txt.ShortcutsEnabled = true;
            this.nomeFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.nomeFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomeFornecedor_txt.TabIndex = 21;
            this.nomeFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomeFornecedor_txt.TextMarginBottom = 0;
            this.nomeFornecedor_txt.TextMarginLeft = 3;
            this.nomeFornecedor_txt.TextMarginTop = 12;
            this.nomeFornecedor_txt.TextPlaceholder = "Digite o nome do fornecedor";
            this.nomeFornecedor_txt.UseSystemPasswordChar = false;
            this.nomeFornecedor_txt.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel10.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel10.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel10.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel10.Location = new System.Drawing.Point(59, 312);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(136, 25);
            this.bunifuLabel10.TabIndex = 41;
            this.bunifuLabel10.Text = "Rua do fornecedor";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel10.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel10.UseGdiPlusTextRendering = true;
            // 
            // ruaFornecedor_txt
            // 
            this.ruaFornecedor_txt.AcceptsReturn = false;
            this.ruaFornecedor_txt.AcceptsTab = false;
            this.ruaFornecedor_txt.AnimationSpeed = 200;
            this.ruaFornecedor_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ruaFornecedor_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ruaFornecedor_txt.AutoSizeHeight = true;
            this.ruaFornecedor_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.ruaFornecedor_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ruaFornecedor_txt.BackgroundImage")));
            this.ruaFornecedor_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.ruaFornecedor_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.ruaFornecedor_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.ruaFornecedor_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.ruaFornecedor_txt.BorderRadius = 16;
            this.ruaFornecedor_txt.BorderThickness = 1;
            this.ruaFornecedor_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.ruaFornecedor_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ruaFornecedor_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaFornecedor_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ruaFornecedor_txt.DefaultText = "";
            this.ruaFornecedor_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.ruaFornecedor_txt.ForeColor = System.Drawing.Color.White;
            this.ruaFornecedor_txt.HideSelection = true;
            this.ruaFornecedor_txt.IconLeft = null;
            this.ruaFornecedor_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaFornecedor_txt.IconPadding = 10;
            this.ruaFornecedor_txt.IconRight = null;
            this.ruaFornecedor_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ruaFornecedor_txt.Lines = new string[0];
            this.ruaFornecedor_txt.Location = new System.Drawing.Point(53, 343);
            this.ruaFornecedor_txt.MaxLength = 32767;
            this.ruaFornecedor_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ruaFornecedor_txt.Modified = false;
            this.ruaFornecedor_txt.Multiline = true;
            this.ruaFornecedor_txt.Name = "ruaFornecedor_txt";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaFornecedor_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ruaFornecedor_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaFornecedor_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ruaFornecedor_txt.OnIdleState = stateProperties28;
            this.ruaFornecedor_txt.Padding = new System.Windows.Forms.Padding(3);
            this.ruaFornecedor_txt.PasswordChar = '\0';
            this.ruaFornecedor_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.ruaFornecedor_txt.PlaceholderText = "Digite a rua do fornecedor";
            this.ruaFornecedor_txt.ReadOnly = false;
            this.ruaFornecedor_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ruaFornecedor_txt.SelectedText = "";
            this.ruaFornecedor_txt.SelectionLength = 0;
            this.ruaFornecedor_txt.SelectionStart = 0;
            this.ruaFornecedor_txt.ShortcutsEnabled = true;
            this.ruaFornecedor_txt.Size = new System.Drawing.Size(419, 59);
            this.ruaFornecedor_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ruaFornecedor_txt.TabIndex = 40;
            this.ruaFornecedor_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ruaFornecedor_txt.TextMarginBottom = 0;
            this.ruaFornecedor_txt.TextMarginLeft = 3;
            this.ruaFornecedor_txt.TextMarginTop = 12;
            this.ruaFornecedor_txt.TextPlaceholder = "Digite a rua do fornecedor";
            this.ruaFornecedor_txt.UseSystemPasswordChar = false;
            this.ruaFornecedor_txt.WordWrap = true;
            // 
            // AdicionarFornecedor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(1143, 642);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.ruaFornecedor_txt);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.emailFornecedor_txt);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.login_button);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.estadoFornecedor_txt);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.cidadeFornecedor_txt);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bairroFornecedor_txt);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.cnpjFornecedor_txt);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.nomeFornecedor_txt);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AdicionarFornecedor";
            this.Text = "khjuhjk";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox nomeFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox cnpjFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox bairroFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox cidadeFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox estadoFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 login_button;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox emailFornecedor_txt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox ruaFornecedor_txt;
    }
}