namespace ProjetoJeffersonADM
{
    partial class Fornecedor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>


        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Fornecedor));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.titulo_label = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.editar_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.apagar_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.refresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pesquisa_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // titulo_label
            // 
            this.titulo_label.AllowParentOverrides = false;
            this.titulo_label.AutoEllipsis = false;
            this.titulo_label.Cursor = System.Windows.Forms.Cursors.Default;
            this.titulo_label.CursorType = System.Windows.Forms.Cursors.Default;
            this.titulo_label.Font = new System.Drawing.Font("Archivo ExtraBold", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.titulo_label.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.titulo_label.Location = new System.Drawing.Point(33, 45);
            this.titulo_label.Name = "titulo_label";
            this.titulo_label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.titulo_label.Size = new System.Drawing.Size(357, 50);
            this.titulo_label.TabIndex = 1;
            this.titulo_label.Text = "Lista de fornecedores";
            this.titulo_label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.titulo_label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.titulo_label.Click += new System.EventHandler(this.titulo_label_Click);
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = true;
            this.bunifuDataGridView1.AllowUserToAddRows = false;
            this.bunifuDataGridView1.AllowUserToDeleteRows = false;
            this.bunifuDataGridView1.AllowUserToOrderColumns = true;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Archivo SemiBold", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Archivo SemiBold", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Archivo SemiBold", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(41, 170);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.ReadOnly = true;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Archivo SemiBold", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView1.RowHeadersVisible = false;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Archivo SemiBold", 9.749999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(1075, 386);
            this.bunifuDataGridView1.TabIndex = 18;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellContentClick);
            // 
            // editar_btn
            // 
            this.editar_btn.AllowAnimations = true;
            this.editar_btn.AllowMouseEffects = true;
            this.editar_btn.AllowToggling = false;
            this.editar_btn.AnimationSpeed = 200;
            this.editar_btn.AutoGenerateColors = false;
            this.editar_btn.AutoRoundBorders = false;
            this.editar_btn.AutoSizeLeftIcon = true;
            this.editar_btn.AutoSizeRightIcon = true;
            this.editar_btn.BackColor = System.Drawing.Color.Transparent;
            this.editar_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("editar_btn.BackgroundImage")));
            this.editar_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.editar_btn.ButtonText = "Editar fornecedor";
            this.editar_btn.ButtonTextMarginLeft = 0;
            this.editar_btn.ColorContrastOnClick = 45;
            this.editar_btn.ColorContrastOnHover = 45;
            this.editar_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.editar_btn.CustomizableEdges = borderEdges1;
            this.editar_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.editar_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.editar_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.editar_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.editar_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.editar_btn.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.editar_btn.ForeColor = System.Drawing.Color.White;
            this.editar_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.editar_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.editar_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.editar_btn.IconMarginLeft = 11;
            this.editar_btn.IconPadding = 10;
            this.editar_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.editar_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.editar_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.editar_btn.IconSize = 25;
            this.editar_btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.IdleBorderRadius = 10;
            this.editar_btn.IdleBorderThickness = 1;
            this.editar_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.IdleIconLeftImage = null;
            this.editar_btn.IdleIconRightImage = null;
            this.editar_btn.IndicateFocus = false;
            this.editar_btn.Location = new System.Drawing.Point(272, 591);
            this.editar_btn.Name = "editar_btn";
            this.editar_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.editar_btn.OnDisabledState.BorderRadius = 10;
            this.editar_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.editar_btn.OnDisabledState.BorderThickness = 1;
            this.editar_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.editar_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.editar_btn.OnDisabledState.IconLeftImage = null;
            this.editar_btn.OnDisabledState.IconRightImage = null;
            this.editar_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.onHoverState.BorderRadius = 10;
            this.editar_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.editar_btn.onHoverState.BorderThickness = 1;
            this.editar_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.editar_btn.onHoverState.IconLeftImage = null;
            this.editar_btn.onHoverState.IconRightImage = null;
            this.editar_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.OnIdleState.BorderRadius = 10;
            this.editar_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.editar_btn.OnIdleState.BorderThickness = 1;
            this.editar_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.editar_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.editar_btn.OnIdleState.IconLeftImage = null;
            this.editar_btn.OnIdleState.IconRightImage = null;
            this.editar_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.editar_btn.OnPressedState.BorderRadius = 10;
            this.editar_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.editar_btn.OnPressedState.BorderThickness = 1;
            this.editar_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.editar_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.editar_btn.OnPressedState.IconLeftImage = null;
            this.editar_btn.OnPressedState.IconRightImage = null;
            this.editar_btn.Size = new System.Drawing.Size(166, 39);
            this.editar_btn.TabIndex = 21;
            this.editar_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.editar_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.editar_btn.TextMarginLeft = 0;
            this.editar_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.editar_btn.UseDefaultRadiusAndThickness = true;
            this.editar_btn.Click += new System.EventHandler(this.editar_btn_Click);
            // 
            // apagar_btn
            // 
            this.apagar_btn.AllowAnimations = true;
            this.apagar_btn.AllowMouseEffects = true;
            this.apagar_btn.AllowToggling = false;
            this.apagar_btn.AnimationSpeed = 200;
            this.apagar_btn.AutoGenerateColors = false;
            this.apagar_btn.AutoRoundBorders = false;
            this.apagar_btn.AutoSizeLeftIcon = true;
            this.apagar_btn.AutoSizeRightIcon = true;
            this.apagar_btn.BackColor = System.Drawing.Color.Transparent;
            this.apagar_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.apagar_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("apagar_btn.BackgroundImage")));
            this.apagar_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dot;
            this.apagar_btn.ButtonText = "Apagar fornecedor";
            this.apagar_btn.ButtonTextMarginLeft = 0;
            this.apagar_btn.ColorContrastOnClick = 45;
            this.apagar_btn.ColorContrastOnHover = 45;
            this.apagar_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.apagar_btn.CustomizableEdges = borderEdges2;
            this.apagar_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.apagar_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.apagar_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.apagar_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.apagar_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.apagar_btn.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.apagar_btn.ForeColor = System.Drawing.Color.White;
            this.apagar_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.apagar_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.apagar_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.apagar_btn.IconMarginLeft = 11;
            this.apagar_btn.IconPadding = 10;
            this.apagar_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.apagar_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.apagar_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.apagar_btn.IconSize = 25;
            this.apagar_btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.apagar_btn.IdleBorderRadius = 10;
            this.apagar_btn.IdleBorderThickness = 1;
            this.apagar_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.apagar_btn.IdleIconLeftImage = null;
            this.apagar_btn.IdleIconRightImage = null;
            this.apagar_btn.IndicateFocus = false;
            this.apagar_btn.Location = new System.Drawing.Point(950, 591);
            this.apagar_btn.Name = "apagar_btn";
            this.apagar_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.apagar_btn.OnDisabledState.BorderRadius = 10;
            this.apagar_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.apagar_btn.OnDisabledState.BorderThickness = 1;
            this.apagar_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.apagar_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.apagar_btn.OnDisabledState.IconLeftImage = null;
            this.apagar_btn.OnDisabledState.IconRightImage = null;
            this.apagar_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.apagar_btn.onHoverState.BorderRadius = 10;
            this.apagar_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.apagar_btn.onHoverState.BorderThickness = 1;
            this.apagar_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.apagar_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.apagar_btn.onHoverState.IconLeftImage = null;
            this.apagar_btn.onHoverState.IconRightImage = null;
            this.apagar_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.apagar_btn.OnIdleState.BorderRadius = 10;
            this.apagar_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dot;
            this.apagar_btn.OnIdleState.BorderThickness = 1;
            this.apagar_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.apagar_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.apagar_btn.OnIdleState.IconLeftImage = null;
            this.apagar_btn.OnIdleState.IconRightImage = null;
            this.apagar_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.apagar_btn.OnPressedState.BorderRadius = 10;
            this.apagar_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.apagar_btn.OnPressedState.BorderThickness = 1;
            this.apagar_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.apagar_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.apagar_btn.OnPressedState.IconLeftImage = null;
            this.apagar_btn.OnPressedState.IconRightImage = null;
            this.apagar_btn.Size = new System.Drawing.Size(166, 39);
            this.apagar_btn.TabIndex = 20;
            this.apagar_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.apagar_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.apagar_btn.TextMarginLeft = 0;
            this.apagar_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.apagar_btn.UseDefaultRadiusAndThickness = true;
            this.apagar_btn.Click += new System.EventHandler(this.apagar_btn_Click);
            // 
            // add_btn
            // 
            this.add_btn.AllowAnimations = true;
            this.add_btn.AllowMouseEffects = true;
            this.add_btn.AllowToggling = false;
            this.add_btn.AnimationSpeed = 200;
            this.add_btn.AutoGenerateColors = false;
            this.add_btn.AutoRoundBorders = false;
            this.add_btn.AutoSizeLeftIcon = true;
            this.add_btn.AutoSizeRightIcon = true;
            this.add_btn.BackColor = System.Drawing.Color.Transparent;
            this.add_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("add_btn.BackgroundImage")));
            this.add_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.add_btn.ButtonText = "Adicionar fornecedor";
            this.add_btn.ButtonTextMarginLeft = 0;
            this.add_btn.ColorContrastOnClick = 45;
            this.add_btn.ColorContrastOnHover = 45;
            this.add_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.add_btn.CustomizableEdges = borderEdges3;
            this.add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.add_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.add_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.add_btn.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.add_btn.ForeColor = System.Drawing.Color.White;
            this.add_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.add_btn.IconMarginLeft = 11;
            this.add_btn.IconPadding = 10;
            this.add_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.add_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.add_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.add_btn.IconSize = 25;
            this.add_btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.IdleBorderRadius = 10;
            this.add_btn.IdleBorderThickness = 1;
            this.add_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.IdleIconLeftImage = null;
            this.add_btn.IdleIconRightImage = null;
            this.add_btn.IndicateFocus = false;
            this.add_btn.Location = new System.Drawing.Point(33, 591);
            this.add_btn.Name = "add_btn";
            this.add_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.add_btn.OnDisabledState.BorderRadius = 10;
            this.add_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.add_btn.OnDisabledState.BorderThickness = 1;
            this.add_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.add_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.add_btn.OnDisabledState.IconLeftImage = null;
            this.add_btn.OnDisabledState.IconRightImage = null;
            this.add_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.BorderRadius = 10;
            this.add_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.add_btn.onHoverState.BorderThickness = 1;
            this.add_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.add_btn.onHoverState.IconLeftImage = null;
            this.add_btn.onHoverState.IconRightImage = null;
            this.add_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.OnIdleState.BorderRadius = 10;
            this.add_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.add_btn.OnIdleState.BorderThickness = 1;
            this.add_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.add_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.add_btn.OnIdleState.IconLeftImage = null;
            this.add_btn.OnIdleState.IconRightImage = null;
            this.add_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.BorderRadius = 10;
            this.add_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.add_btn.OnPressedState.BorderThickness = 1;
            this.add_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.add_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.add_btn.OnPressedState.IconLeftImage = null;
            this.add_btn.OnPressedState.IconRightImage = null;
            this.add_btn.Size = new System.Drawing.Size(174, 39);
            this.add_btn.TabIndex = 17;
            this.add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.add_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.add_btn.TextMarginLeft = 0;
            this.add_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.add_btn.UseDefaultRadiusAndThickness = true;
            this.add_btn.Click += new System.EventHandler(this.add_btn_Click_1);
            // 
            // refresh
            // 
            this.refresh.AllowAnimations = true;
            this.refresh.AllowMouseEffects = true;
            this.refresh.AllowToggling = false;
            this.refresh.AnimationSpeed = 200;
            this.refresh.AutoGenerateColors = false;
            this.refresh.AutoRoundBorders = false;
            this.refresh.AutoSizeLeftIcon = true;
            this.refresh.AutoSizeRightIcon = true;
            this.refresh.BackColor = System.Drawing.Color.Transparent;
            this.refresh.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("refresh.BackgroundImage")));
            this.refresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.refresh.ButtonText = "Atualizar";
            this.refresh.ButtonTextMarginLeft = 0;
            this.refresh.ColorContrastOnClick = 45;
            this.refresh.ColorContrastOnHover = 45;
            this.refresh.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.refresh.CustomizableEdges = borderEdges4;
            this.refresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.refresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.refresh.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.refresh.ForeColor = System.Drawing.Color.White;
            this.refresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.refresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.refresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.refresh.IconMarginLeft = 11;
            this.refresh.IconPadding = 10;
            this.refresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.refresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.refresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.refresh.IconSize = 25;
            this.refresh.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.IdleBorderRadius = 10;
            this.refresh.IdleBorderThickness = 1;
            this.refresh.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.IdleIconLeftImage = null;
            this.refresh.IdleIconRightImage = null;
            this.refresh.IndicateFocus = false;
            this.refresh.Location = new System.Drawing.Point(341, 113);
            this.refresh.Name = "refresh";
            this.refresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refresh.OnDisabledState.BorderRadius = 10;
            this.refresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.refresh.OnDisabledState.BorderThickness = 1;
            this.refresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refresh.OnDisabledState.IconLeftImage = null;
            this.refresh.OnDisabledState.IconRightImage = null;
            this.refresh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.onHoverState.BorderRadius = 10;
            this.refresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.refresh.onHoverState.BorderThickness = 1;
            this.refresh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.onHoverState.ForeColor = System.Drawing.Color.White;
            this.refresh.onHoverState.IconLeftImage = null;
            this.refresh.onHoverState.IconRightImage = null;
            this.refresh.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.OnIdleState.BorderRadius = 10;
            this.refresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.refresh.OnIdleState.BorderThickness = 1;
            this.refresh.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.refresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.refresh.OnIdleState.IconLeftImage = null;
            this.refresh.OnIdleState.IconRightImage = null;
            this.refresh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.refresh.OnPressedState.BorderRadius = 10;
            this.refresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.refresh.OnPressedState.BorderThickness = 1;
            this.refresh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.refresh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.refresh.OnPressedState.IconLeftImage = null;
            this.refresh.OnPressedState.IconRightImage = null;
            this.refresh.Size = new System.Drawing.Size(97, 39);
            this.refresh.TabIndex = 16;
            this.refresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.refresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.refresh.TextMarginLeft = 0;
            this.refresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.refresh.UseDefaultRadiusAndThickness = true;
            this.refresh.Click += new System.EventHandler(this.refresh_Click);
            // 
            // pesquisa_txt
            // 
            this.pesquisa_txt.AcceptsReturn = false;
            this.pesquisa_txt.AcceptsTab = false;
            this.pesquisa_txt.AnimationSpeed = 200;
            this.pesquisa_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.pesquisa_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.pesquisa_txt.AutoSizeHeight = true;
            this.pesquisa_txt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.pesquisa_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pesquisa_txt.BackgroundImage")));
            this.pesquisa_txt.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pesquisa_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pesquisa_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.pesquisa_txt.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.pesquisa_txt.BorderRadius = 24;
            this.pesquisa_txt.BorderThickness = 1;
            this.pesquisa_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.pesquisa_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.pesquisa_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.pesquisa_txt.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pesquisa_txt.DefaultText = "";
            this.pesquisa_txt.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.pesquisa_txt.ForeColor = System.Drawing.Color.White;
            this.pesquisa_txt.HideSelection = true;
            this.pesquisa_txt.IconLeft = null;
            this.pesquisa_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.pesquisa_txt.IconPadding = 10;
            this.pesquisa_txt.IconRight = global::ProjetoJeffersonADM.Properties.Resources.icons8_search_50;
            this.pesquisa_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.pesquisa_txt.Lines = new string[0];
            this.pesquisa_txt.Location = new System.Drawing.Point(33, 113);
            this.pesquisa_txt.MaxLength = 32767;
            this.pesquisa_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.pesquisa_txt.Modified = false;
            this.pesquisa_txt.Multiline = true;
            this.pesquisa_txt.Name = "pesquisa_txt";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pesquisa_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.pesquisa_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pesquisa_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pesquisa_txt.OnIdleState = stateProperties4;
            this.pesquisa_txt.Padding = new System.Windows.Forms.Padding(3);
            this.pesquisa_txt.PasswordChar = '\0';
            this.pesquisa_txt.PlaceholderForeColor = System.Drawing.Color.White;
            this.pesquisa_txt.PlaceholderText = "Pesquisa";
            this.pesquisa_txt.ReadOnly = false;
            this.pesquisa_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.pesquisa_txt.SelectedText = "";
            this.pesquisa_txt.SelectionLength = 0;
            this.pesquisa_txt.SelectionStart = 0;
            this.pesquisa_txt.ShortcutsEnabled = true;
            this.pesquisa_txt.Size = new System.Drawing.Size(280, 39);
            this.pesquisa_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.pesquisa_txt.TabIndex = 15;
            this.pesquisa_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.pesquisa_txt.TextMarginBottom = 0;
            this.pesquisa_txt.TextMarginLeft = 3;
            this.pesquisa_txt.TextMarginTop = 4;
            this.pesquisa_txt.TextPlaceholder = "Pesquisa";
            this.pesquisa_txt.UseSystemPasswordChar = false;
            this.pesquisa_txt.WordWrap = true;
            // 
            // Fornecedor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.ClientSize = new System.Drawing.Size(1143, 642);
            this.Controls.Add(this.editar_btn);
            this.Controls.Add(this.apagar_btn);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.add_btn);
            this.Controls.Add(this.refresh);
            this.Controls.Add(this.pesquisa_txt);
            this.Controls.Add(this.titulo_label);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Fornecedor";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Produtos";
            this.Load += new System.EventHandler(this.Fornecedor_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel titulo_label;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox pesquisa_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 refresh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 add_btn;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 apagar_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 editar_btn;
    }
}