namespace ProjetoJeffersonADM
{
    partial class Registro
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Registro));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuSnackbar2 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuSnackbar3 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuSnackbar4 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.nomeLoja_field = new Bunifu.UI.WinForms.BunifuTextBox();
            this.register_button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.login_button = new System.Windows.Forms.LinkLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cnpj_field = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.email_field = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.contato_field = new Bunifu.UI.WinForms.BunifuTextBox();
            this.password_field = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSnackbar5 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Archivo Black", 30F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(34, 42);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(441, 60);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Acesse a plataforma";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel1.UseGdiPlusTextRendering = true;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.Red;
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Archivo", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MessageTopMargin = 0;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuSnackbar2
            // 
            this.bunifuSnackbar2.AllowDragging = false;
            this.bunifuSnackbar2.AllowMultipleViews = true;
            this.bunifuSnackbar2.ClickToClose = true;
            this.bunifuSnackbar2.DoubleClickToClose = true;
            this.bunifuSnackbar2.DurationAfterIdle = 3000;
            this.bunifuSnackbar2.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar2.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon4")));
            this.bunifuSnackbar2.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.FadeCloseIcon = false;
            this.bunifuSnackbar2.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar2.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon5")));
            this.bunifuSnackbar2.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.Margin = 10;
            this.bunifuSnackbar2.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar2.MaximumViews = 7;
            this.bunifuSnackbar2.MessageRightMargin = 15;
            this.bunifuSnackbar2.MessageTopMargin = 0;
            this.bunifuSnackbar2.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar2.ShowBorders = false;
            this.bunifuSnackbar2.ShowCloseIcon = false;
            this.bunifuSnackbar2.ShowIcon = true;
            this.bunifuSnackbar2.ShowShadows = true;
            this.bunifuSnackbar2.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar2.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon6")));
            this.bunifuSnackbar2.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.ViewsMargin = 7;
            this.bunifuSnackbar2.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar2.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon7")));
            this.bunifuSnackbar2.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.ZoomCloseIcon = true;
            // 
            // bunifuSnackbar3
            // 
            this.bunifuSnackbar3.AllowDragging = false;
            this.bunifuSnackbar3.AllowMultipleViews = true;
            this.bunifuSnackbar3.ClickToClose = true;
            this.bunifuSnackbar3.DoubleClickToClose = true;
            this.bunifuSnackbar3.DurationAfterIdle = 3000;
            this.bunifuSnackbar3.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar3.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon8")));
            this.bunifuSnackbar3.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.FadeCloseIcon = false;
            this.bunifuSnackbar3.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar3.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon9")));
            this.bunifuSnackbar3.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.Margin = 10;
            this.bunifuSnackbar3.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar3.MaximumViews = 7;
            this.bunifuSnackbar3.MessageRightMargin = 15;
            this.bunifuSnackbar3.MessageTopMargin = 0;
            this.bunifuSnackbar3.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar3.ShowBorders = false;
            this.bunifuSnackbar3.ShowCloseIcon = false;
            this.bunifuSnackbar3.ShowIcon = true;
            this.bunifuSnackbar3.ShowShadows = true;
            this.bunifuSnackbar3.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar3.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon10")));
            this.bunifuSnackbar3.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.ViewsMargin = 7;
            this.bunifuSnackbar3.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar3.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon11")));
            this.bunifuSnackbar3.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.ZoomCloseIcon = true;
            // 
            // bunifuSnackbar4
            // 
            this.bunifuSnackbar4.AllowDragging = false;
            this.bunifuSnackbar4.AllowMultipleViews = true;
            this.bunifuSnackbar4.ClickToClose = true;
            this.bunifuSnackbar4.DoubleClickToClose = true;
            this.bunifuSnackbar4.DurationAfterIdle = 3000;
            this.bunifuSnackbar4.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar4.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon12")));
            this.bunifuSnackbar4.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.FadeCloseIcon = false;
            this.bunifuSnackbar4.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar4.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon13")));
            this.bunifuSnackbar4.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.Margin = 10;
            this.bunifuSnackbar4.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar4.MaximumViews = 7;
            this.bunifuSnackbar4.MessageRightMargin = 15;
            this.bunifuSnackbar4.MessageTopMargin = 0;
            this.bunifuSnackbar4.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar4.ShowBorders = false;
            this.bunifuSnackbar4.ShowCloseIcon = false;
            this.bunifuSnackbar4.ShowIcon = true;
            this.bunifuSnackbar4.ShowShadows = true;
            this.bunifuSnackbar4.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar4.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon14")));
            this.bunifuSnackbar4.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.ViewsMargin = 7;
            this.bunifuSnackbar4.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar4.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon15")));
            this.bunifuSnackbar4.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.ZoomCloseIcon = true;
            // 
            // nomeLoja_field
            // 
            this.nomeLoja_field.AcceptsReturn = false;
            this.nomeLoja_field.AcceptsTab = false;
            this.nomeLoja_field.AnimationSpeed = 200;
            this.nomeLoja_field.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomeLoja_field.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomeLoja_field.AutoSizeHeight = true;
            this.nomeLoja_field.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeLoja_field.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomeLoja_field.BackgroundImage")));
            this.nomeLoja_field.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeLoja_field.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeLoja_field.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.nomeLoja_field.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.nomeLoja_field.BorderRadius = 16;
            this.nomeLoja_field.BorderThickness = 1;
            this.nomeLoja_field.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomeLoja_field.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomeLoja_field.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeLoja_field.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomeLoja_field.DefaultText = "";
            this.nomeLoja_field.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.nomeLoja_field.ForeColor = System.Drawing.Color.White;
            this.nomeLoja_field.HideSelection = true;
            this.nomeLoja_field.IconLeft = null;
            this.nomeLoja_field.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeLoja_field.IconPadding = 10;
            this.nomeLoja_field.IconRight = null;
            this.nomeLoja_field.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomeLoja_field.Lines = new string[0];
            this.nomeLoja_field.Location = new System.Drawing.Point(34, 216);
            this.nomeLoja_field.MaxLength = 32767;
            this.nomeLoja_field.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomeLoja_field.Modified = false;
            this.nomeLoja_field.Multiline = true;
            this.nomeLoja_field.Name = "nomeLoja_field";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeLoja_field.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomeLoja_field.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeLoja_field.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomeLoja_field.OnIdleState = stateProperties4;
            this.nomeLoja_field.Padding = new System.Windows.Forms.Padding(3);
            this.nomeLoja_field.PasswordChar = '\0';
            this.nomeLoja_field.PlaceholderForeColor = System.Drawing.Color.White;
            this.nomeLoja_field.PlaceholderText = "Digite o nome da sua loja";
            this.nomeLoja_field.ReadOnly = false;
            this.nomeLoja_field.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomeLoja_field.SelectedText = "";
            this.nomeLoja_field.SelectionLength = 0;
            this.nomeLoja_field.SelectionStart = 0;
            this.nomeLoja_field.ShortcutsEnabled = true;
            this.nomeLoja_field.Size = new System.Drawing.Size(419, 59);
            this.nomeLoja_field.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomeLoja_field.TabIndex = 14;
            this.nomeLoja_field.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomeLoja_field.TextMarginBottom = 0;
            this.nomeLoja_field.TextMarginLeft = 3;
            this.nomeLoja_field.TextMarginTop = 12;
            this.nomeLoja_field.TextPlaceholder = "Digite o nome da sua loja";
            this.nomeLoja_field.UseSystemPasswordChar = false;
            this.nomeLoja_field.WordWrap = true;
            // 
            // register_button
            // 
            this.register_button.AllowAnimations = true;
            this.register_button.AllowMouseEffects = true;
            this.register_button.AllowToggling = false;
            this.register_button.AnimationSpeed = 200;
            this.register_button.AutoGenerateColors = false;
            this.register_button.AutoRoundBorders = false;
            this.register_button.AutoSizeLeftIcon = true;
            this.register_button.AutoSizeRightIcon = true;
            this.register_button.BackColor = System.Drawing.Color.Transparent;
            this.register_button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("register_button.BackgroundImage")));
            this.register_button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_button.ButtonText = "Registrar-se";
            this.register_button.ButtonTextMarginLeft = 0;
            this.register_button.ColorContrastOnClick = 45;
            this.register_button.ColorContrastOnHover = 45;
            this.register_button.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.register_button.CustomizableEdges = borderEdges1;
            this.register_button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.register_button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.register_button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.register_button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.register_button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.register_button.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.register_button.ForeColor = System.Drawing.Color.White;
            this.register_button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.register_button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.register_button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.register_button.IconMarginLeft = 11;
            this.register_button.IconPadding = 10;
            this.register_button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.register_button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.register_button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.register_button.IconSize = 25;
            this.register_button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.IdleBorderRadius = 10;
            this.register_button.IdleBorderThickness = 1;
            this.register_button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.IdleIconLeftImage = null;
            this.register_button.IdleIconRightImage = null;
            this.register_button.IndicateFocus = false;
            this.register_button.Location = new System.Drawing.Point(501, 550);
            this.register_button.Name = "register_button";
            this.register_button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.register_button.OnDisabledState.BorderRadius = 10;
            this.register_button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_button.OnDisabledState.BorderThickness = 1;
            this.register_button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.register_button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.register_button.OnDisabledState.IconLeftImage = null;
            this.register_button.OnDisabledState.IconRightImage = null;
            this.register_button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.onHoverState.BorderRadius = 10;
            this.register_button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_button.onHoverState.BorderThickness = 1;
            this.register_button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.register_button.onHoverState.IconLeftImage = null;
            this.register_button.onHoverState.IconRightImage = null;
            this.register_button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.OnIdleState.BorderRadius = 10;
            this.register_button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_button.OnIdleState.BorderThickness = 1;
            this.register_button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.register_button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.register_button.OnIdleState.IconLeftImage = null;
            this.register_button.OnIdleState.IconRightImage = null;
            this.register_button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.register_button.OnPressedState.BorderRadius = 10;
            this.register_button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_button.OnPressedState.BorderThickness = 1;
            this.register_button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.register_button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.register_button.OnPressedState.IconLeftImage = null;
            this.register_button.OnPressedState.IconRightImage = null;
            this.register_button.Size = new System.Drawing.Size(147, 39);
            this.register_button.TabIndex = 13;
            this.register_button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.register_button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.register_button.TextMarginLeft = 0;
            this.register_button.TextPadding = new System.Windows.Forms.Padding(0);
            this.register_button.UseDefaultRadiusAndThickness = true;
            this.register_button.Click += new System.EventHandler(this.register_button_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(557, 401);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(138, 25);
            this.bunifuLabel2.TabIndex = 17;
            this.bunifuLabel2.Text = "Ja tem uma conta?";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // login_button
            // 
            this.login_button.ActiveLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.AutoSize = true;
            this.login_button.Font = new System.Drawing.Font("Archivo", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.login_button.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.Location = new System.Drawing.Point(701, 401);
            this.login_button.Name = "login_button";
            this.login_button.Size = new System.Drawing.Size(158, 25);
            this.login_button.TabIndex = 18;
            this.login_button.TabStop = true;
            this.login_button.Text = "Entrar na sua conta";
            this.login_button.UseMnemonic = false;
            this.login_button.VisitedLinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.login_button.Click += new System.EventHandler(this.login_button_Click);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(34, 98);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(366, 50);
            this.bunifuLabel3.TabIndex = 19;
            this.bunifuLabel3.Text = "Faça login ou registre-se para comecar a gerenciar \r\nsua loja ainda hoje.\r\n";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(36, 185);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(101, 25);
            this.bunifuLabel4.TabIndex = 20;
            this.bunifuLabel4.Text = "Nome da loja:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel4.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(36, 419);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(65, 25);
            this.bunifuLabel5.TabIndex = 21;
            this.bunifuLabel5.Text = "Contato:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel5.UseGdiPlusTextRendering = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(34, 298);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(39, 25);
            this.bunifuLabel6.TabIndex = 23;
            this.bunifuLabel6.Text = "Cnpj:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel6.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel6.UseGdiPlusTextRendering = true;
            // 
            // cnpj_field
            // 
            this.cnpj_field.AcceptsReturn = false;
            this.cnpj_field.AcceptsTab = false;
            this.cnpj_field.AnimationSpeed = 200;
            this.cnpj_field.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cnpj_field.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cnpj_field.AutoSizeHeight = true;
            this.cnpj_field.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cnpj_field.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cnpj_field.BackgroundImage")));
            this.cnpj_field.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpj_field.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpj_field.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.cnpj_field.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.cnpj_field.BorderRadius = 16;
            this.cnpj_field.BorderThickness = 1;
            this.cnpj_field.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cnpj_field.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cnpj_field.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpj_field.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cnpj_field.DefaultText = "";
            this.cnpj_field.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.cnpj_field.ForeColor = System.Drawing.Color.White;
            this.cnpj_field.HideSelection = true;
            this.cnpj_field.IconLeft = null;
            this.cnpj_field.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpj_field.IconPadding = 10;
            this.cnpj_field.IconRight = null;
            this.cnpj_field.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpj_field.Lines = new string[0];
            this.cnpj_field.Location = new System.Drawing.Point(34, 329);
            this.cnpj_field.MaxLength = 50;
            this.cnpj_field.MinimumSize = new System.Drawing.Size(1, 1);
            this.cnpj_field.Modified = false;
            this.cnpj_field.Multiline = true;
            this.cnpj_field.Name = "cnpj_field";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpj_field.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cnpj_field.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpj_field.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpj_field.OnIdleState = stateProperties8;
            this.cnpj_field.Padding = new System.Windows.Forms.Padding(3);
            this.cnpj_field.PasswordChar = '\0';
            this.cnpj_field.PlaceholderForeColor = System.Drawing.Color.White;
            this.cnpj_field.PlaceholderText = "Digite seu cnpj";
            this.cnpj_field.ReadOnly = false;
            this.cnpj_field.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cnpj_field.SelectedText = "";
            this.cnpj_field.SelectionLength = 0;
            this.cnpj_field.SelectionStart = 0;
            this.cnpj_field.ShortcutsEnabled = true;
            this.cnpj_field.Size = new System.Drawing.Size(419, 59);
            this.cnpj_field.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cnpj_field.TabIndex = 22;
            this.cnpj_field.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cnpj_field.TextMarginBottom = 0;
            this.cnpj_field.TextMarginLeft = 3;
            this.cnpj_field.TextMarginTop = 12;
            this.cnpj_field.TextPlaceholder = "Digite seu cnpj";
            this.cnpj_field.UseSystemPasswordChar = false;
            this.cnpj_field.WordWrap = true;
            this.cnpj_field.TextChange += new System.EventHandler(this.cnpj_field_TextChanged_1);
            this.cnpj_field.TextChanged += new System.EventHandler(this.cnpj_field_TextChanged);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(551, 185);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(52, 25);
            this.bunifuLabel7.TabIndex = 25;
            this.bunifuLabel7.Text = "E-mail:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel7.UseGdiPlusTextRendering = true;
            // 
            // email_field
            // 
            this.email_field.AcceptsReturn = false;
            this.email_field.AcceptsTab = false;
            this.email_field.AnimationSpeed = 200;
            this.email_field.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.email_field.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.email_field.AutoSizeHeight = true;
            this.email_field.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.email_field.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("email_field.BackgroundImage")));
            this.email_field.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.email_field.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.email_field.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.email_field.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.email_field.BorderRadius = 16;
            this.email_field.BorderThickness = 1;
            this.email_field.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.email_field.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.email_field.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.email_field.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.email_field.DefaultText = "";
            this.email_field.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.email_field.ForeColor = System.Drawing.Color.White;
            this.email_field.HideSelection = true;
            this.email_field.IconLeft = null;
            this.email_field.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.email_field.IconPadding = 10;
            this.email_field.IconRight = null;
            this.email_field.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.email_field.Lines = new string[0];
            this.email_field.Location = new System.Drawing.Point(551, 216);
            this.email_field.MaxLength = 32767;
            this.email_field.MinimumSize = new System.Drawing.Size(1, 1);
            this.email_field.Modified = false;
            this.email_field.Multiline = true;
            this.email_field.Name = "email_field";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_field.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.email_field.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_field.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_field.OnIdleState = stateProperties12;
            this.email_field.Padding = new System.Windows.Forms.Padding(3);
            this.email_field.PasswordChar = '\0';
            this.email_field.PlaceholderForeColor = System.Drawing.Color.White;
            this.email_field.PlaceholderText = "Digite seu e-mail";
            this.email_field.ReadOnly = false;
            this.email_field.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.email_field.SelectedText = "";
            this.email_field.SelectionLength = 0;
            this.email_field.SelectionStart = 0;
            this.email_field.ShortcutsEnabled = true;
            this.email_field.Size = new System.Drawing.Size(419, 59);
            this.email_field.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.email_field.TabIndex = 24;
            this.email_field.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.email_field.TextMarginBottom = 0;
            this.email_field.TextMarginLeft = 3;
            this.email_field.TextMarginTop = 12;
            this.email_field.TextPlaceholder = "Digite seu e-mail";
            this.email_field.UseSystemPasswordChar = false;
            this.email_field.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Archivo SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(551, 298);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(52, 25);
            this.bunifuLabel8.TabIndex = 27;
            this.bunifuLabel8.Text = "Senha:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel8.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;
            this.bunifuLabel8.UseGdiPlusTextRendering = true;
            // 
            // contato_field
            // 
            this.contato_field.AcceptsReturn = false;
            this.contato_field.AcceptsTab = false;
            this.contato_field.AnimationSpeed = 200;
            this.contato_field.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.contato_field.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.contato_field.AutoSizeHeight = true;
            this.contato_field.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.contato_field.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("contato_field.BackgroundImage")));
            this.contato_field.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.contato_field.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.contato_field.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.contato_field.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.contato_field.BorderRadius = 16;
            this.contato_field.BorderThickness = 1;
            this.contato_field.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.contato_field.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.contato_field.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.contato_field.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.contato_field.DefaultText = "";
            this.contato_field.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.contato_field.ForeColor = System.Drawing.Color.White;
            this.contato_field.HideSelection = true;
            this.contato_field.IconLeft = null;
            this.contato_field.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.contato_field.IconPadding = 10;
            this.contato_field.IconRight = null;
            this.contato_field.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.contato_field.Lines = new string[0];
            this.contato_field.Location = new System.Drawing.Point(34, 450);
            this.contato_field.MaxLength = 22;
            this.contato_field.MinimumSize = new System.Drawing.Size(1, 1);
            this.contato_field.Modified = false;
            this.contato_field.Multiline = true;
            this.contato_field.Name = "contato_field";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contato_field.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.contato_field.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contato_field.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contato_field.OnIdleState = stateProperties16;
            this.contato_field.Padding = new System.Windows.Forms.Padding(3);
            this.contato_field.PasswordChar = '\0';
            this.contato_field.PlaceholderForeColor = System.Drawing.Color.White;
            this.contato_field.PlaceholderText = "Digite seu contato";
            this.contato_field.ReadOnly = false;
            this.contato_field.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.contato_field.SelectedText = "";
            this.contato_field.SelectionLength = 0;
            this.contato_field.SelectionStart = 0;
            this.contato_field.ShortcutsEnabled = true;
            this.contato_field.Size = new System.Drawing.Size(419, 59);
            this.contato_field.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.contato_field.TabIndex = 28;
            this.contato_field.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.contato_field.TextMarginBottom = 0;
            this.contato_field.TextMarginLeft = 3;
            this.contato_field.TextMarginTop = 12;
            this.contato_field.TextPlaceholder = "Digite seu contato";
            this.contato_field.UseSystemPasswordChar = false;
            this.contato_field.WordWrap = true;
            this.contato_field.TextChange += new System.EventHandler(this.contato_field_TextChanged);
            // 
            // password_field
            // 
            this.password_field.AcceptsReturn = false;
            this.password_field.AcceptsTab = false;
            this.password_field.AnimationSpeed = 200;
            this.password_field.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.password_field.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.password_field.AutoSizeHeight = true;
            this.password_field.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.password_field.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("password_field.BackgroundImage")));
            this.password_field.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.password_field.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.password_field.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.password_field.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.password_field.BorderRadius = 16;
            this.password_field.BorderThickness = 1;
            this.password_field.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.password_field.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.password_field.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.password_field.DefaultFont = new System.Drawing.Font("Archivo Medium", 12F, System.Drawing.FontStyle.Bold);
            this.password_field.DefaultText = "";
            this.password_field.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            this.password_field.ForeColor = System.Drawing.Color.White;
            this.password_field.HideSelection = true;
            this.password_field.IconLeft = null;
            this.password_field.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.password_field.IconPadding = 10;
            this.password_field.IconRight = null;
            this.password_field.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.password_field.Lines = new string[0];
            this.password_field.Location = new System.Drawing.Point(551, 329);
            this.password_field.MaxLength = 32767;
            this.password_field.MinimumSize = new System.Drawing.Size(1, 1);
            this.password_field.Modified = false;
            this.password_field.Multiline = true;
            this.password_field.Name = "password_field";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_field.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.password_field.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_field.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(27)))), ((int)(((byte)(27)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_field.OnIdleState = stateProperties20;
            this.password_field.Padding = new System.Windows.Forms.Padding(3);
            this.password_field.PasswordChar = '\0';
            this.password_field.PlaceholderForeColor = System.Drawing.Color.White;
            this.password_field.PlaceholderText = "Digite sua senha";
            this.password_field.ReadOnly = false;
            this.password_field.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.password_field.SelectedText = "";
            this.password_field.SelectionLength = 0;
            this.password_field.SelectionStart = 0;
            this.password_field.ShortcutsEnabled = true;
            this.password_field.Size = new System.Drawing.Size(419, 59);
            this.password_field.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.password_field.TabIndex = 29;
            this.password_field.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.password_field.TextMarginBottom = 0;
            this.password_field.TextMarginLeft = 3;
            this.password_field.TextMarginTop = 12;
            this.password_field.TextPlaceholder = "Digite sua senha";
            this.password_field.UseSystemPasswordChar = false;
            this.password_field.WordWrap = true;
            // 
            // bunifuSnackbar5
            // 
            this.bunifuSnackbar5.AllowDragging = false;
            this.bunifuSnackbar5.AllowMultipleViews = true;
            this.bunifuSnackbar5.ClickToClose = true;
            this.bunifuSnackbar5.DoubleClickToClose = true;
            this.bunifuSnackbar5.DurationAfterIdle = 3000;
            this.bunifuSnackbar5.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar5.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar5.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar5.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar5.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon16")));
            this.bunifuSnackbar5.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar5.FadeCloseIcon = false;
            this.bunifuSnackbar5.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar5.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar5.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar5.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar5.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon17")));
            this.bunifuSnackbar5.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar5.Margin = 10;
            this.bunifuSnackbar5.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar5.MaximumViews = 7;
            this.bunifuSnackbar5.MessageRightMargin = 15;
            this.bunifuSnackbar5.MessageTopMargin = 0;
            this.bunifuSnackbar5.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar5.ShowBorders = false;
            this.bunifuSnackbar5.ShowCloseIcon = false;
            this.bunifuSnackbar5.ShowIcon = true;
            this.bunifuSnackbar5.ShowShadows = true;
            this.bunifuSnackbar5.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar5.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar5.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar5.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar5.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon18")));
            this.bunifuSnackbar5.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar5.ViewsMargin = 7;
            this.bunifuSnackbar5.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar5.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar5.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar5.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar5.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar5.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar5.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar5.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon19")));
            this.bunifuSnackbar5.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar5.ZoomCloseIcon = true;
            // 
            // Registro
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.ClientSize = new System.Drawing.Size(1143, 642);
            this.Controls.Add(this.password_field);
            this.Controls.Add(this.contato_field);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.email_field);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.cnpj_field);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.login_button);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.nomeLoja_field);
            this.Controls.Add(this.register_button);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Registro";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login";
            this.Load += new System.EventHandler(this.Registro_Load);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Registro_MouseDown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.Registro_MouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.Registro_MouseUp);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 register_button;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar2;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar3;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar4;
        private Bunifu.UI.WinForms.BunifuTextBox nomeLoja_field;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.LinkLabel login_button;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox cnpj_field;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox email_field;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox contato_field;
        private Bunifu.UI.WinForms.BunifuTextBox password_field;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar5;
    }
}