namespace ProjetoJeffersonADM.Logins
{
    partial class Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuAnimatorNS.Animation animation1 = new Bunifu.UI.WinForms.BunifuAnimatorNS.Animation();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.text2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.register_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.label1 = new System.Windows.Forms.Label();
            this.login_button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuSnackbar2 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuSnackbar3 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.loginEmail_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.loginSenha_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSnackbar4 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuTransition1 = new Bunifu.UI.WinForms.BunifuTransition(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.text2);
            this.bunifuGradientPanel1.Controls.Add(this.register_btn);
            this.bunifuGradientPanel1.Controls.Add(this.label2);
            this.bunifuTransition1.SetDecoration(this.bunifuGradientPanel1, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(-1, -37);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(285, 679);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // text2
            // 
            this.text2.AllowParentOverrides = false;
            this.text2.AutoEllipsis = false;
            this.text2.Cursor = System.Windows.Forms.Cursors.Default;
            this.text2.CursorType = System.Windows.Forms.Cursors.Default;
            this.text2.Font = new System.Drawing.Font("Raleway", 26F, System.Drawing.FontStyle.Bold);
            this.text2.ForeColor = System.Drawing.Color.White;
            this.text2.Location = new System.Drawing.Point(41, 205);
            this.text2.Name = "text2";
            this.text2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.text2.Size = new System.Drawing.Size(135, 96);
            this.text2.TabIndex = 14;
            this.text2.Text = "Crie sua \r\nconta!";
            this.text2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.text2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // register_btn
            // 
            this.register_btn.AllowAnimations = true;
            this.register_btn.AllowMouseEffects = true;
            this.register_btn.AllowToggling = false;
            this.register_btn.AnimationSpeed = 200;
            this.register_btn.AutoGenerateColors = false;
            this.register_btn.AutoRoundBorders = false;
            this.register_btn.AutoSizeLeftIcon = true;
            this.register_btn.AutoSizeRightIcon = true;
            this.register_btn.BackColor = System.Drawing.Color.Transparent;
            this.register_btn.BackColor1 = System.Drawing.Color.Transparent;
            this.register_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("register_btn.BackgroundImage")));
            this.register_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_btn.ButtonText = "SE REGISTRE";
            this.register_btn.ButtonTextMarginLeft = 0;
            this.register_btn.ColorContrastOnClick = 45;
            this.register_btn.ColorContrastOnHover = 45;
            this.register_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.register_btn.CustomizableEdges = borderEdges3;
            this.bunifuTransition1.SetDecoration(this.register_btn, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.register_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.register_btn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.register_btn.DisabledFillColor = System.Drawing.Color.Transparent;
            this.register_btn.DisabledForecolor = System.Drawing.Color.Transparent;
            this.register_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.register_btn.Font = new System.Drawing.Font("Roboto Medium", 9.75F);
            this.register_btn.ForeColor = System.Drawing.Color.White;
            this.register_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.register_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.register_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.register_btn.IconMarginLeft = 11;
            this.register_btn.IconPadding = 10;
            this.register_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.register_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.register_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.register_btn.IconSize = 25;
            this.register_btn.IdleBorderColor = System.Drawing.Color.White;
            this.register_btn.IdleBorderRadius = 20;
            this.register_btn.IdleBorderThickness = 1;
            this.register_btn.IdleFillColor = System.Drawing.Color.Transparent;
            this.register_btn.IdleIconLeftImage = null;
            this.register_btn.IdleIconRightImage = null;
            this.register_btn.IndicateFocus = false;
            this.register_btn.Location = new System.Drawing.Point(41, 476);
            this.register_btn.Name = "register_btn";
            this.register_btn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.register_btn.OnDisabledState.BorderRadius = 20;
            this.register_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_btn.OnDisabledState.BorderThickness = 1;
            this.register_btn.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.register_btn.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.register_btn.OnDisabledState.IconLeftImage = null;
            this.register_btn.OnDisabledState.IconRightImage = null;
            this.register_btn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.register_btn.onHoverState.BorderRadius = 20;
            this.register_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_btn.onHoverState.BorderThickness = 1;
            this.register_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.register_btn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.register_btn.onHoverState.IconLeftImage = null;
            this.register_btn.onHoverState.IconRightImage = null;
            this.register_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.register_btn.OnIdleState.BorderRadius = 20;
            this.register_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_btn.OnIdleState.BorderThickness = 1;
            this.register_btn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.register_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.register_btn.OnIdleState.IconLeftImage = null;
            this.register_btn.OnIdleState.IconRightImage = null;
            this.register_btn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.register_btn.OnPressedState.BorderRadius = 20;
            this.register_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.register_btn.OnPressedState.BorderThickness = 1;
            this.register_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.register_btn.OnPressedState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.register_btn.OnPressedState.IconLeftImage = null;
            this.register_btn.OnPressedState.IconRightImage = null;
            this.register_btn.Size = new System.Drawing.Size(168, 39);
            this.register_btn.TabIndex = 9;
            this.register_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.register_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.register_btn.TextMarginLeft = 0;
            this.register_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.register_btn.UseDefaultRadiusAndThickness = true;
            this.register_btn.Click += new System.EventHandler(this.register_btn_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Raleway Medium", 10F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(37, 329);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(157, 38);
            this.label2.TabIndex = 9;
            this.label2.Text = "Venha criar uma conta\npara sua loja!!";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Raleway", 30F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(471, 91);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(390, 55);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Bem-vindo de volta!";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Raleway SemiBold", 8.25F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.SystemColors.GrayText;
            this.label1.Location = new System.Drawing.Point(573, 149);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(172, 16);
            this.label1.TabIndex = 4;
            this.label1.Text = "Preencha com os dados da loja";
            this.label1.Click += new System.EventHandler(this.label1_Click);
            // 
            // login_button
            // 
            this.login_button.AllowAnimations = true;
            this.login_button.AllowMouseEffects = true;
            this.login_button.AllowToggling = false;
            this.login_button.AnimationSpeed = 200;
            this.login_button.AutoGenerateColors = false;
            this.login_button.AutoRoundBorders = false;
            this.login_button.AutoSizeLeftIcon = true;
            this.login_button.AutoSizeRightIcon = true;
            this.login_button.BackColor = System.Drawing.Color.Transparent;
            this.login_button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.login_button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("login_button.BackgroundImage")));
            this.login_button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.ButtonText = "ENTRAR";
            this.login_button.ButtonTextMarginLeft = 0;
            this.login_button.ColorContrastOnClick = 45;
            this.login_button.ColorContrastOnHover = 45;
            this.login_button.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.login_button.CustomizableEdges = borderEdges4;
            this.bunifuTransition1.SetDecoration(this.login_button, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.login_button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.login_button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.login_button.Font = new System.Drawing.Font("Roboto Medium", 9.75F);
            this.login_button.ForeColor = System.Drawing.Color.White;
            this.login_button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.login_button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.login_button.IconMarginLeft = 11;
            this.login_button.IconPadding = 10;
            this.login_button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.login_button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.login_button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.login_button.IconSize = 25;
            this.login_button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.login_button.IdleBorderRadius = 10;
            this.login_button.IdleBorderThickness = 1;
            this.login_button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.login_button.IdleIconLeftImage = null;
            this.login_button.IdleIconRightImage = null;
            this.login_button.IndicateFocus = false;
            this.login_button.Location = new System.Drawing.Point(566, 439);
            this.login_button.Name = "login_button";
            this.login_button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.login_button.OnDisabledState.BorderRadius = 10;
            this.login_button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnDisabledState.BorderThickness = 1;
            this.login_button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.login_button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.login_button.OnDisabledState.IconLeftImage = null;
            this.login_button.OnDisabledState.IconRightImage = null;
            this.login_button.onHoverState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.login_button.onHoverState.BorderRadius = 10;
            this.login_button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.onHoverState.BorderThickness = 1;
            this.login_button.onHoverState.FillColor = System.Drawing.Color.MidnightBlue;
            this.login_button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.login_button.onHoverState.IconLeftImage = null;
            this.login_button.onHoverState.IconRightImage = null;
            this.login_button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.BorderRadius = 10;
            this.login_button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnIdleState.BorderThickness = 1;
            this.login_button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(26)))), ((int)(((byte)(255)))));
            this.login_button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnIdleState.IconLeftImage = null;
            this.login_button.OnIdleState.IconRightImage = null;
            this.login_button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.BorderRadius = 10;
            this.login_button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.login_button.OnPressedState.BorderThickness = 1;
            this.login_button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.login_button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.login_button.OnPressedState.IconLeftImage = null;
            this.login_button.OnPressedState.IconRightImage = null;
            this.login_button.Size = new System.Drawing.Size(214, 39);
            this.login_button.TabIndex = 13;
            this.login_button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.login_button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.login_button.TextMarginLeft = 0;
            this.login_button.TextPadding = new System.Windows.Forms.Padding(0);
            this.login_button.UseDefaultRadiusAndThickness = true;
            this.login_button.Click += new System.EventHandler(this.login_button_Click);
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MessageTopMargin = 0;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuSnackbar2
            // 
            this.bunifuSnackbar2.AllowDragging = false;
            this.bunifuSnackbar2.AllowMultipleViews = true;
            this.bunifuSnackbar2.ClickToClose = true;
            this.bunifuSnackbar2.DoubleClickToClose = true;
            this.bunifuSnackbar2.DurationAfterIdle = 3000;
            this.bunifuSnackbar2.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar2.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon4")));
            this.bunifuSnackbar2.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.FadeCloseIcon = false;
            this.bunifuSnackbar2.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar2.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon5")));
            this.bunifuSnackbar2.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.Margin = 10;
            this.bunifuSnackbar2.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar2.MaximumViews = 7;
            this.bunifuSnackbar2.MessageRightMargin = 15;
            this.bunifuSnackbar2.MessageTopMargin = 0;
            this.bunifuSnackbar2.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar2.ShowBorders = false;
            this.bunifuSnackbar2.ShowCloseIcon = false;
            this.bunifuSnackbar2.ShowIcon = true;
            this.bunifuSnackbar2.ShowShadows = true;
            this.bunifuSnackbar2.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar2.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon6")));
            this.bunifuSnackbar2.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.ViewsMargin = 7;
            this.bunifuSnackbar2.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar2.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar2.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar2.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar2.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar2.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar2.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar2.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon7")));
            this.bunifuSnackbar2.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar2.ZoomCloseIcon = true;
            // 
            // bunifuSnackbar3
            // 
            this.bunifuSnackbar3.AllowDragging = false;
            this.bunifuSnackbar3.AllowMultipleViews = true;
            this.bunifuSnackbar3.ClickToClose = true;
            this.bunifuSnackbar3.DoubleClickToClose = true;
            this.bunifuSnackbar3.DurationAfterIdle = 3000;
            this.bunifuSnackbar3.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar3.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon8")));
            this.bunifuSnackbar3.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.FadeCloseIcon = false;
            this.bunifuSnackbar3.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar3.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon9")));
            this.bunifuSnackbar3.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.Margin = 10;
            this.bunifuSnackbar3.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar3.MaximumViews = 7;
            this.bunifuSnackbar3.MessageRightMargin = 15;
            this.bunifuSnackbar3.MessageTopMargin = 0;
            this.bunifuSnackbar3.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar3.ShowBorders = false;
            this.bunifuSnackbar3.ShowCloseIcon = false;
            this.bunifuSnackbar3.ShowIcon = true;
            this.bunifuSnackbar3.ShowShadows = true;
            this.bunifuSnackbar3.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar3.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon10")));
            this.bunifuSnackbar3.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.ViewsMargin = 7;
            this.bunifuSnackbar3.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar3.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar3.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar3.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar3.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar3.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar3.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar3.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon11")));
            this.bunifuSnackbar3.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar3.ZoomCloseIcon = true;
            // 
            // loginEmail_txt
            // 
            this.loginEmail_txt.AcceptsReturn = false;
            this.loginEmail_txt.AcceptsTab = false;
            this.loginEmail_txt.AnimationSpeed = 200;
            this.loginEmail_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.loginEmail_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.loginEmail_txt.AutoSizeHeight = false;
            this.loginEmail_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.loginEmail_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginEmail_txt.BackgroundImage")));
            this.loginEmail_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.loginEmail_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginEmail_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginEmail_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.loginEmail_txt.BorderRadius = 1;
            this.loginEmail_txt.BorderThickness = 0;
            this.loginEmail_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.loginEmail_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.loginEmail_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.loginEmail_txt, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.loginEmail_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.loginEmail_txt.DefaultText = "";
            this.loginEmail_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.loginEmail_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.loginEmail_txt.HideSelection = true;
            this.loginEmail_txt.IconLeft = null;
            this.loginEmail_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginEmail_txt.IconPadding = 10;
            this.loginEmail_txt.IconRight = null;
            this.loginEmail_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginEmail_txt.Lines = new string[0];
            this.loginEmail_txt.Location = new System.Drawing.Point(496, 292);
            this.loginEmail_txt.MaxLength = 32767;
            this.loginEmail_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.loginEmail_txt.Modified = false;
            this.loginEmail_txt.Multiline = true;
            this.loginEmail_txt.Name = "loginEmail_txt";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginEmail_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.loginEmail_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginEmail_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties12.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginEmail_txt.OnIdleState = stateProperties12;
            this.loginEmail_txt.Padding = new System.Windows.Forms.Padding(3);
            this.loginEmail_txt.PasswordChar = '\0';
            this.loginEmail_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.loginEmail_txt.PlaceholderText = "Email";
            this.loginEmail_txt.ReadOnly = false;
            this.loginEmail_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.loginEmail_txt.SelectedText = "";
            this.loginEmail_txt.SelectionLength = 0;
            this.loginEmail_txt.SelectionStart = 0;
            this.loginEmail_txt.ShortcutsEnabled = true;
            this.loginEmail_txt.Size = new System.Drawing.Size(349, 26);
            this.loginEmail_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.loginEmail_txt.TabIndex = 15;
            this.loginEmail_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.loginEmail_txt.TextMarginBottom = 0;
            this.loginEmail_txt.TextMarginLeft = 3;
            this.loginEmail_txt.TextMarginTop = 0;
            this.loginEmail_txt.TextPlaceholder = "Email";
            this.loginEmail_txt.UseSystemPasswordChar = false;
            this.loginEmail_txt.WordWrap = true;
            // 
            // loginSenha_txt
            // 
            this.loginSenha_txt.AcceptsReturn = false;
            this.loginSenha_txt.AcceptsTab = false;
            this.loginSenha_txt.AnimationSpeed = 200;
            this.loginSenha_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.loginSenha_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.loginSenha_txt.AutoSizeHeight = false;
            this.loginSenha_txt.BackColor = System.Drawing.Color.WhiteSmoke;
            this.loginSenha_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginSenha_txt.BackgroundImage")));
            this.loginSenha_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.loginSenha_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginSenha_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginSenha_txt.BorderColorIdle = System.Drawing.Color.WhiteSmoke;
            this.loginSenha_txt.BorderRadius = 1;
            this.loginSenha_txt.BorderThickness = 0;
            this.loginSenha_txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.loginSenha_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.loginSenha_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.loginSenha_txt, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.loginSenha_txt.DefaultFont = new System.Drawing.Font("Raleway SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.loginSenha_txt.DefaultText = "";
            this.loginSenha_txt.FillColor = System.Drawing.Color.WhiteSmoke;
            this.loginSenha_txt.ForeColor = System.Drawing.SystemColors.Desktop;
            this.loginSenha_txt.HideSelection = true;
            this.loginSenha_txt.IconLeft = null;
            this.loginSenha_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginSenha_txt.IconPadding = 10;
            this.loginSenha_txt.IconRight = null;
            this.loginSenha_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginSenha_txt.Lines = new string[0];
            this.loginSenha_txt.Location = new System.Drawing.Point(496, 363);
            this.loginSenha_txt.MaxLength = 100;
            this.loginSenha_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.loginSenha_txt.Modified = false;
            this.loginSenha_txt.Multiline = false;
            this.loginSenha_txt.Name = "loginSenha_txt";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginSenha_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.loginSenha_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginSenha_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties16.ForeColor = System.Drawing.SystemColors.Desktop;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginSenha_txt.OnIdleState = stateProperties16;
            this.loginSenha_txt.Padding = new System.Windows.Forms.Padding(3);
            this.loginSenha_txt.PasswordChar = '\0';
            this.loginSenha_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.loginSenha_txt.PlaceholderText = "Senha";
            this.loginSenha_txt.ReadOnly = false;
            this.loginSenha_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.loginSenha_txt.SelectedText = "";
            this.loginSenha_txt.SelectionLength = 0;
            this.loginSenha_txt.SelectionStart = 0;
            this.loginSenha_txt.ShortcutsEnabled = true;
            this.loginSenha_txt.Size = new System.Drawing.Size(349, 26);
            this.loginSenha_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.loginSenha_txt.TabIndex = 16;
            this.loginSenha_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.loginSenha_txt.TextMarginBottom = 0;
            this.loginSenha_txt.TextMarginLeft = 3;
            this.loginSenha_txt.TextMarginTop = 0;
            this.loginSenha_txt.TextPlaceholder = "Senha";
            this.loginSenha_txt.UseSystemPasswordChar = true;
            this.loginSenha_txt.WordWrap = true;
            // 
            // bunifuSnackbar4
            // 
            this.bunifuSnackbar4.AllowDragging = false;
            this.bunifuSnackbar4.AllowMultipleViews = true;
            this.bunifuSnackbar4.ClickToClose = true;
            this.bunifuSnackbar4.DoubleClickToClose = true;
            this.bunifuSnackbar4.DurationAfterIdle = 3000;
            this.bunifuSnackbar4.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar4.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon12")));
            this.bunifuSnackbar4.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.FadeCloseIcon = false;
            this.bunifuSnackbar4.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar4.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon13")));
            this.bunifuSnackbar4.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.Margin = 10;
            this.bunifuSnackbar4.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar4.MaximumViews = 7;
            this.bunifuSnackbar4.MessageRightMargin = 15;
            this.bunifuSnackbar4.MessageTopMargin = 0;
            this.bunifuSnackbar4.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar4.ShowBorders = false;
            this.bunifuSnackbar4.ShowCloseIcon = false;
            this.bunifuSnackbar4.ShowIcon = true;
            this.bunifuSnackbar4.ShowShadows = true;
            this.bunifuSnackbar4.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar4.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon14")));
            this.bunifuSnackbar4.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.ViewsMargin = 7;
            this.bunifuSnackbar4.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar4.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar4.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar4.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar4.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar4.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar4.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar4.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon15")));
            this.bunifuSnackbar4.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar4.ZoomCloseIcon = true;
            // 
            // bunifuTransition1
            // 
            this.bunifuTransition1.AnimationType = Bunifu.UI.WinForms.BunifuAnimatorNS.AnimationType.Scale;
            this.bunifuTransition1.Cursor = null;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuTransition1.DefaultAnimation = animation1;
            // 
            // Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(965, 642);
            this.Controls.Add(this.loginSenha_txt);
            this.Controls.Add(this.loginEmail_txt);
            this.Controls.Add(this.login_button);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Login";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login";
            this.Load += new System.EventHandler(this.Login_Load);
            this.Click += new System.EventHandler(this.Login_Click);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Login_MouseDown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.Login_MouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.Login_MouseUp);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 register_btn;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 login_button;
        private Bunifu.UI.WinForms.BunifuLabel text2;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar2;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar3;
        private Bunifu.UI.WinForms.BunifuTextBox loginEmail_txt;
        private Bunifu.UI.WinForms.BunifuTextBox loginSenha_txt;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar4;
        private Bunifu.UI.WinForms.BunifuTransition bunifuTransition1;
    }
}